Feat/queue
kysect/Shreks pull request #106
Opened 2022-08-17 15:59 UTC by ronimizy

2022-08-17 19:13 UTC, FrediKats requested changes
Я не понял решения.

1. Мы обсуждали фильтры и я ожидал, что это будут какие-то максимально простые спецификации, а в итоге в PR визиторы, над которыми нужно прям сидеть, чтобы понять.
2. Логика определения приоритетов превратилась в иерархию из SubmissionEvaluator'ов, которые нужны ради вызова визитора ISubmissionEvaluatorVisitor в котором к тому же и не используется. Я не уверен, то мы получим профит от переусложения, но явно получим потом проблемы с тем, чтобы эти сложные абстракции поддерживать.

2022-08-17 19:14 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/GetSubmissionDeadlineHandler.cs
> +            .Where(x => x.Id.Equals(request.SubmissionId));
Да

2022-08-17 19:14 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/GetSubmissionDeadlineHandler.cs
> +            .Where(x => x.Id.Equals(request.SubmissionId));
Тест же есть на этот хендлер....

2022-08-17 19:15 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/GetSubmissionDeadlineHandler.cs
> +            .Where(x => x.Students.Any(xx => studentsQuery.Contains(xx)));
Есть тест, дед....

2022-08-17 19:16 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application/Queue/SubmissionRatingEvaluatorVisitor.cs
> +        return deadline.Deadline > submission.SubmissionDateTime ? 1 : 0;
Потому что приоритет сабмишена в очереди это `int`, а не `bool`

2022-08-17 19:20 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application/Queue/SubmissionRatingEvaluatorVisitor.cs
> +        return deadline.Deadline > submission.SubmissionDateTime ? 1 : 0;
в данной ситуации он бинарный, да. но при других сортерах может и не быть таковым.

2022-08-17 19:34 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Extensions/EnumerableExtensions.cs
> +        this IEnumerable<T> enumerable,
Для рекурсивного метода, нужно изначальный ``IEumerable`1`` переделать в ``IAsyncEnumerable`1``

2022-08-17 19:56 UTC, ronimizy commented on Source/Tests/Kysect.Shreks.Tests/DataAccess/SubmissionTest.cs
> +        var _ = studentGenerator.GeneratedEntities;
ну типа того, а то без этого разъёбывается так как сабмишен дёргает GroupAssignment.Group.Student, а студент ы в группу добавляются в генераторе студентов.

2022-08-17 20:00 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/DatabaseSeeders/IDatabaseSeeder.cs
> +
Ну да, но, хочется чтобы не было крестика красного, а была зелёная галочка

2022-08-17 20:09 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/ISubmissionEvaluatorVisitor.cs
> +public interface ISubmissionEvaluatorVisitor<T>
ну, если у нас появится сущность в которой есть логика оценивания сабмита (кроме сущности [в виде гномика] ментора, которая тыкает коменты на гх) можно будет сделать дестинейшн тип у его визитёра каким-нибудь VO, чтобы их друг от друга отделить.

2022-08-17 21:39 UTC, ronimizy commented
Ну, реализованные сейчас фильтры и визиторы это самое простое и первое что пришло мне в голову чтобы показать что и то и другое может юзать и данные относящиеся к сабмишену, и данные получаемые через контракты приложения, чтобы показать зачем нужно отделение логики в визиторы от сущности. 

Насчёт иерархии не знаю, у нас есть один базовый тип и остальные не связанные больше ни с чем кроме базового типа, теоретически это можно назвать иерархией, везде где есть наследование есть иерархия, но тут она одноуровневая.

2022-08-17 21:41 UTC, ronimizy commented
Визиторы и из создание, вынос в слой приложения делались из соображений того что у нас могут быть более сложные фильтры и критерии сортировки: например лаба по которой еще не прошёл дедлайн

2022-08-17 23:38 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/ISubmissionEvaluatorVisitor.cs
> +public interface ISubmissionEvaluatorVisitor<T>
А ISubmissionEvaluator и этот визитор это какие-то совсем абстрактные штуки, которые по сабмишену что-то вычисляют и возвращают?
Какие у нас еще будут, кроме как под приоритет в очереди?

2022-08-17 23:38 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application/Queue/SubmissionRatingEvaluatorVisitor.cs
> +public class SubmissionRatingEvaluatorVisitor : ISubmissionEvaluatorVisitor<int>
Ну вот тут-то уже priority, нет?

2022-08-17 23:38 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/IQueueFilterVisitor.cs
> +public interface IQueueFilterVisitor<T>
Если честно, вообще не понимаю, зачем тут визитор и почему это не могло быть прямо в фильтре
У нас планируются какие-то реализации, кроме той, что докидывает в Queryable фильтрацию?

2022-08-17 23:38 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
Подожди, откуда там BFS возьмется?
Я может что-то не распарсил, но этот класс же литерали итератор

2022-08-17 23:38 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
> +        IQueryable<Submission> submissionsQuery,
А что сюда изначально будет передаваться?

2022-08-18 06:11 UTC, FrediKats commented on Source/Domain/Kysect.Shreks.Core/Extensions/EnumerableExtensions.cs
> +        this IEnumerable<T> enumerable,
А что за рекурсивный метод, где он используется и зачем ему async?

2022-08-18 06:11 UTC, FrediKats commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
А откуда у нас BFS и DFS? У нас же плоские списки, нет графа.

2022-08-18 06:22 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Extensions/EnumerableExtensions.cs
> +        this IEnumerable<T> enumerable,
Самый главный метод в пр… метод обновления очереди

2022-08-18 06:22 UTC, FrediKats commented
Мне кажется, что визиторы - это не совсем тот инструмент, который нужно применять для того, чтобы отсортировать коллекцию. И как итог, решение полуилось сильно переусложнённым - откуда-то появились bfs даже. Я предположу, что графы появились из-за того, что у нас несколько уровней сортировки, но тут стоит заметить, то нам НЕ нужно эту графовую структуру хранить, а это просто итерация сортировки. Его точно также можно развернуть в компаратор на несколько правил.

Может посмотреть в сторону написания компаратора? Кажется, что в задаче это и нужно. Его также можно поделить на части - собирать из правил. Например:
```
var submissions = GetAllubmissions(...);
var comparator = new Comparator(
  new DeadlineOrderRule(...),
  new SubmissionDateOrderRule(...));

submissions = submissions.OrderBy(comparator);
```

И как будто бы всё.

2022-08-18 06:27 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/IQueryExecutor.cs
> +    Task<IReadOnlyCollection<T>> ExecuteAsync<T>(IQueryable<T> query, CancellationToken cancellationToken);
`.ToListAsync` это метод еф, этот интерфейс нужен чтобы не тащить еф в домен.

2022-08-18 06:27 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/ISubmissionEvaluatorVisitor.cs
> +public interface ISubmissionEvaluatorVisitor<T>
Скорее всего никаких

2022-08-18 06:27 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application/Queue/SubmissionRatingEvaluatorVisitor.cs
> +public class SubmissionRatingEvaluatorVisitor : ISubmissionEvaluatorVisitor<int>
Да, Priority лучше подходит

2022-08-18 06:28 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/SubmissionQueue.cs
> +        IQueryable<Submission> submissionsQuery,
Дб сет сабмишенов

2022-08-18 06:30 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/IQueueFilterVisitor.cs
> +public interface IQueueFilterVisitor<T>
Например фильтрация по "текущей" лабе, там не получится ограничится данными доставаемыми из самого сабмишена.

2022-08-18 13:59 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
Все, понял, зачем это - если сортировать рекурсивно (как сейчас и сделано), то енумератор не подходит, потому что будет двигаться с каждым вызовом и в итоге мы получим полностью пройденный енумератор, когда отсортируем полностью только первую часть по всем критериям
А эта структурка умеет копироваться на next, в отличие от енумератора

Но кстати как я понял, можно было через skip и take сделать (сомнительно конечно, но и это бы не пришлось городить)

2022-08-18 14:07 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
> Но кстати как я понял, можно было через skip и take сделать (сомнительно конечно, но и это бы не пришлось городить)

помянем перф

2022-08-18 14:16 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
Так если я правильно прочитал, то они ничего не копируют и делают readonly view листа

2022-08-18 14:24 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
В любом случае норм решение, но StepperCollection как-то непонятно звучит
Кажется стоит назвать так, чтобы было понятно, что это енумератор с возможностью копирования стейта итерации
Так сказать можешь назвать forward_iterator, я пойму)0

2022-08-18 14:37 UTC, darksidersstrife commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/ISubmissionEvaluatorVisitor.cs
> +public interface ISubmissionEvaluatorVisitor<T>
Вот и мне так кажется
Так что вполне мог быть priority evaluator

А еще я правильно понимаю, что раз в очереди все эвалюуаторы возвращают int, то при сортировке по дате оно будет преобразовывать в миллисекунды?
Точнее это-то норм, но вдруг мы когда-нибудь по какому-нибудь даблу захотим сортить

2022-08-18 14:40 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Models/StepperCollection.cs
> +public readonly record struct StepperCollection<T>
> Так если я правильно прочитал, то они ничего не копируют и делают readonly view листа

ну типа да, но у тебя асимптотика n будет для получения каждого элемента

2022-08-18 14:43 UTC, darksidersstrife commented
Я вот тоже примерно так это видел
Неужели так плохо, если правила сортировки будут внутри запрашивать данные по дедлайнам и другим вещам?
Или так как они сущности (а это все же справедливо, как-то перзиститься они должны), им нельзя прокинуть медиатор/дбконтекст, потому что ужас, абстракции текут?)

2022-08-18 14:52 UTC, ronimizy commented
> Я вот тоже примерно так это видел
> Неужели так плохо, если правила сортировки будут внутри запрашивать данные по дедлайнам и другим вещам?
> Или так как они сущности (а это все же справедливо, как-то перзиститься они должны), им нельзя прокинуть медиатор/дбконтекст, потому что ужас, абстракции текут?)

Дбконтекст ты не прокинешь из-за циклических зависимостей, а закидывать его в сам домен ну это уже прям совсем плохо. Не говоря о том, что эти предложения ломают структуру многослойной архитектуры и в будущем точно приведут к тому что поддерживать это будет очень тяжело.

2022-08-18 15:13 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Queue/Visitors/ISubmissionEvaluatorVisitor.cs
> +public interface ISubmissionEvaluatorVisitor<T>
Логику сравнения можно в принципе отвязать от конкретного типа по которому оно идёт. Залил.

2022-08-18 17:10 UTC, FrediKats commented
По результатам созвона пришли к "Очень хорошо, но переделайте".

2022-08-19 05:24 UTC, FrediKats approved these changes

2022-08-19 05:24 UTC, FrediKats commented on Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
> +    protected virtual IReadOnlyCollection<QueueFilter> Filters { get; init; }
Меня немного смущает, что к ассайменту теперь фильтры привязаны, но у меня нет ещё понимания что и как должно лежать. Нужно будет обсудить.

2022-08-19 05:26 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Study/Assignment.cs
> +    protected virtual IReadOnlyCollection<QueueFilter> Filters { get; init; }
Эта такая же ситуация как с группами. На 7 дотнете уберём, ща сюда тоже тудушку добавлю

2022-08-19 09:18 UTC, merged