Feat: Concurrent Table Access
kysect/Shreks pull request #108
Opened 2022-08-18 13:22 UTC by Mihinator3000

2022-08-18 14:38 UTC, ronimizy requested changes
По реализации гугл штук пройдусь позже. Оч грустно что опять плохой кодстайл, излишние аннотации типов в одном место, `new()` в другом. 

По аксессору. Тут на самом деле надо бы подумать. Кмк стоит сделать какой-нибудь background worker, который будет раз в n у.е. времени флашить накопившиеся обновления. 

В текущей реализации всё смешано в кучу. Предлагаю разбить её на компоненты:
1. `GoogleTableAccessor` - сервис с самой реализацией метода обновления для одного айдишника.
2. `GoogleTableAccessorWorker` - сервис, который будет собирать запросы (в нём будут хранится хеш сеты [можно не делать даже отдельную модельку для сета, а сихнронизировать на семафорах внутри воркера] и инстанс `IGoogleTableAccessor` в который будут передаваться вызовы в момент флаша)

В di это добавим декораторами через Scrutor, ну или просто ручками через конкертные типы, там главное не проиграть в вызовы методов, в принципе я могу это сделать.

2022-08-18 14:38 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
Никогда не возвращай доменные сущности из хендлеров. 
Делай дто.

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +            }
При создании сообщений логера не стоит юзать интерполяцию строк.

```suggestion
            try
            {
                var query = new GetCoursePointsBySubjectCourse.Query(courseId);
                var response = await _mediator.Send(query, token);

                var points = response.Points;
                var spreadsheetId = await GetSpreadsheetIdAsync(courseId, token);
                await _pointsSheet.UpdateAsync(spreadsheetId, points, token);

                _logger.LogInformation("Successfully updated points sheet of course {CourseId}.", courseId);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Failed to update points sheet of course {CourseId}.", courseId);
            }
```

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        IReadOnlyCollection<Guid> subjectCourseIds = PointsUpdateSubjectCourseIds.GetAndClearValues();
```suggestion
        var subjectCourseIds = PointsUpdateSubjectCourseIds.GetAndClearValues();
```

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
```suggestion
        var subjectCourseIds = QueueUpdateSubjectCourseIds.GetAndClearValues();

        if (!subjectCourseIds.Any())
        {
            QueueUpdateSemaphore.Release();
            return;
        }
```

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +            }
```suggestion
            try
            {
                var queue = new StudentsQueue(Array.Empty<Submission>());

                //TODO: change to GetStudentQueueBySubjectCourse call

                var spreadsheetId = await GetSpreadsheetIdAsync(courseId, token);
                await _queueSheet.UpdateAsync(spreadsheetId, queue, token);

                _logger.LogInformation("Successfully updated queue sheet of course {CourseId}.", courseId);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Failed to update queue sheet of course {CourseId}.", courseId);
            }
```

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +
Это не должно быть статикой от слова совсем, ты же сервис в коллекцию добавляешь синглтоном, это твоя точка контроля лайфтайма объекта в системе.

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +
Максимальные значения семафора по единичкам тоже поставь

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _mediator.Send(new AddGoogleTableSubjectCourseAssociation.Query(subjectCourseId, spreadsheetId), token);
```suggestion
        var spreadsheetId = await _sheetManagementService.CreateSpreadsheetAsync(token);
        var query = new AddGoogleTableSubjectCourseAssociation.Query(subjectCourseId, spreadsheetId);
        await _mediator.Send(query, token);
```

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/Collection/ConcurrentHashSet.cs
> +﻿namespace Kysect.Shreks.Integration.Google.Tools.Collection;
лучше сделай папку `Models` в корне проекта и кинь туда

2022-08-18 14:38 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
А вот это тебе надо будет объяснить. Ты сделал так, что есть вероятность сгенерить одинаковые SubjectCourseGroup

2022-08-18 15:26 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +            }
А можно узнать почему так?

2022-08-18 15:28 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +            }
На самом деле, строка которую ты передаёшь это темплейт. С правильной реализацией ты оставляешь информацию об имени параметра в темплейте, плюс не аллоцируешь много строк. 

https://www.youtube.com/watch?v=6zoMd_FwSwQ

2022-08-18 15:34 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
Тогда такой вопрос, у нас разве Response не является своего рода дто? Если же проблема в том что я просто возвращаю доменные сущности, то я так уже делал CoursePoints, или там какая-то другая ситуация?

2022-08-18 15:52 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
CoursePoints это модель приложения, пойдёт под определение дто. 
В моём понимании дто это объекты которые возвращаешься из приложения, а респонс это грубо говоря "транспорт" на котором они оттуда приходят)

2022-08-18 15:58 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
Звучит слегка странно, респонс в таком случае кажется не очень полезной оберткой

2022-08-18 16:01 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
Такова модель медиатора. Сейчас у нас достаточно простые квери, поэтому может показаться что респонс не нужен, но когда надо будет вернуть из квери несколько дто, то будет логичнее иметь респонс вместо того чтобы создавать агрегирующее дто.

2022-08-18 16:05 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetGoogleTableSubjectCourseAssociation.cs
> +    public record Response(GoogleTableSubjectCourseAssociation? GoogleTableAssociation);
Ок, понял

2022-08-18 16:13 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
В какой смысле одинаковые, я чет не выкупаю

2022-08-18 17:14 UTC, Mihinator3000 commented
Не очень понял как данные должны попадать в бэкграунд воркер, типа добавить ему не асинхронные методы для добавления нового CourseId для последующего апдейта?

2022-08-18 17:51 UTC, ronimizy commented
воркер имплементит `IGoogleTableAccessor`, везде где достаётся `IGoogleTableAccessor` будет доставаться инстанс воркера. только его методы будут не выполнять обновление, а кешировать данные на основе которых будет выполняться обновление. а уже сам метод выполнения в воркере будет выполнять обновление по закешированным данным вызывая методы у `GoogleTableAccessor`.

2022-08-18 18:16 UTC, FrediKats commented
Можем созвониться и обсудить, если что-то глобальное. А то по комментам сложно собрать картину, мне кажется.

2022-08-18 18:20 UTC, Mihinator3000 commented
> Можем созвониться и обсудить, если что-то глобальное. А то по комментам сложно собрать картину, мне кажется.

Я вроде понял что @ronimizy имел в виду с бэкграунд воркером, если да, то наверное остается только проблема с драйвом, если Гоша сам не посмотрит, то можем созвониться и обсудить

2022-08-18 18:50 UTC, ronimizy requested changes
Еп, именно то, что я имел в виду

2022-08-18 18:50 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetSpreadsheetIdBySubjectCourse.cs
> +}
`Get` нотация подразумевает выкидывания эксепшена если объект не найден

2022-08-18 18:50 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessorWorker.cs
> +            }
Почитай про `Task.WhenAll`

2022-08-18 18:50 UTC, ronimizy commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +var driverService = new DriveService(initializer);
ДА НЕ УМЕР ОН В КОНЦЕ ДРАЙВА

2022-08-18 18:51 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
В смысле не будет? Работает же, я запускал)

2022-08-18 18:57 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Ну, во первых, ты не добавляешь хостед сервис. Далее, для хостед сервиса нужно указать тип, тип `GoogleTableAccessorWorker` ты не регаешь его в самом контейнере, у тебя зарегана пара (`IGoogleTableAccessor`, `GoogleTableAccessorWorker`), т.е. если просто к твоему коду добавить `.AddHostedService<GoogleTableAccessorWorker>()` оно упадёт, потому что не сможет разрезолвить. Надо по любому добавлять явно `GoogleTableAccessorWorker` в коллекцию, но с декорейтом оно не будет работать, потому что уйдёт в в петлю резолвов (`GoogleTableAccessorWorker` -> `IGoogleTableAccessor` => `GoogleTableAccessorWorker` -> ...)

2022-08-18 18:57 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Чтобы всё корректно работало, тебе нужно чтобы выполнялся такой кондишен:

```cs
var accessor = p.GetRequiredService<IGoogleTableAccessor>();
var worker = p.GetRequiredService<GoogleTableAccessorWorker>();

Console.WriteLine(accessor.Equals(worker));
```

2022-08-18 19:03 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        IReadOnlyCollection<Guid> subjectCourseIds = PointsUpdateSubjectCourseIds.GetAndClearValues();
Не evident же)

2022-08-18 19:25 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        _spreadsheetCreationSemaphore = new SemaphoreSlim(1, 1);
Семафор на 1 элемент - это же мьютекс, да?

2022-08-18 19:25 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
Раз уж мы увязались в примитивы синхронизации, то fyi в кейсах, когда метод один раз иницилазируется, можно уменьшить время на локах за счёт double check - https://csharpindepth.com/Articles/Singleton

2022-08-18 19:27 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
ну тут ты чёт загнул. всё-таки запрос к базе по времени дольше чем взятие семафора)

2022-08-18 19:28 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
@ronimizy тут еще ответь тогда

2022-08-18 19:29 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
Ну в рамках одного курса не может быть двух одинаковых групп)

2022-08-18 19:30 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
А где там группы одинаковые то..

2022-08-18 19:31 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        _spreadsheetCreationSemaphore = new SemaphoreSlim(1, 1);
Ну типа, но мьютекс должен релизится тем же потоком, поэтому для синхронизации асинхронного кода не подходит

2022-08-18 19:33 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
в случае, если количество SubjectCourseGroup больше чем количество StudentGroup

2022-08-18 19:34 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
это совсем не кейс с синглтоном.

2022-08-18 19:45 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
хоотяяяяя, мб да, имеет смысл так сделать)

2022-08-18 19:47 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
я чёт изначально подумал что ты другой сценарий имеешь в виду

2022-08-18 19:58 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
Это на 28 строчке то? То что до меня там было написано?

2022-08-18 19:59 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
Не важно дольше ли. Ты на каждый запрос гарантировано идёшь в базу. Но можешь избавиться от взятия лока. Но как ты правильно заметил, поход в базу тут сильно дольше и мы даже не заметим профита. Это скорее на случай, если @Mihinator3000 решит завтра сесть писать свой тред пул!

2022-08-18 20:00 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubjectCourseGroupGenerator.cs
> +        var subjectCourse = _faker.PickRandom<SubjectCourse>(_subjectCourseGenerator.GeneratedEntities);
Оставь как было короче. Там все правильно написано. Зачем ты это менял?

2022-08-18 20:02 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
Не не не, в базу мы гарантированно идём, но зато если таблицы будут созданы, то их получение разными потоками будет независимо, так что только если она не создана поток будет в авейт уходить. Если дабл чека не будет, то потоки будут получать инфу последовательно, хотя могли бы параллельно.

2022-08-18 20:03 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        await _spreadsheetCreationSemaphore.WaitAsync(token);
Так что во всех случаях, когда таблица создана (подавляющее большинство) будет сильный профит.

2022-08-18 20:12 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Когда в асп сервер добавим, оно само будет запускать.

2022-08-18 20:14 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
А, ок

2022-08-18 20:28 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
На самом деле теперь я не понимаю, зачем же мы теперь наследуемся от IGoogleTableAccessor, где асинк методы должны быть, может лучше сделать интерфейс типа IGoogleTableAccessorWorker с обычными void методами?

2022-08-18 20:33 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Эт вопрос абстракции, тем кто юзает аксессор не нужно ничего знать про воркер. Немного не стандартный прокси)
В асинк методах не вижу никакой проблемы.

2022-08-18 20:35 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Ну мы просто будем писать при вызове типа await _tableAccessor.UpdatePointsAsync(id, token) вместо _tableAccessor.UpdatePoints(id) или типа того, мне кажется это логичнее + если метод переименовать будет сразу понятно что происходит, и никто не будет думать почему же таблица сию секунду не обновилась

2022-08-18 20:41 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Не совсем понимаю, как то, что мы уберём таску и асинк из названия, даст понять, что операция выполнится не сразу же?
То что мы собираем на обновление какое-то количество объектов, а не делаем это сразу, это детали реализации. Абстракция не всегда должна их отражать, она наоборот отделят пользователя апи от них.

2022-08-18 20:44 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Я написал что если переименовать метод, то будет понятно. Абстракция это конечно хорошо, но мне кажется в этом моменте просто лишний код получается без какой либо причины

2022-08-18 20:45 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
А лишний код это? Возврат `Task.CompletedTask`?

2022-08-18 20:49 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Это await _tableAccessor.UpdatePointsAsync(id, token), а не что-то вроде _tableAccessorWorker.AddCourseToPointsUpdate(id);

2022-08-18 20:50 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Меня беспокоит не количество символов, а ненужные места, типа await и token

2022-08-18 20:51 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Ну, кмк это не страшно. Добавлять новую абстракцию в этом случае хуже. 
Не думаю что это должно быть частью этого пр, чтобы не затягивать, можешь вынести на обсуждение в дискорде, если считаешь это проблемой.

2022-08-18 20:52 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
@FrediKats можешь сказать что по этому поводу думаешь?

2022-08-19 06:00 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
> +            .Decorate<IGoogleTableAccessor, GoogleTableAccessorWorker>();
Мне поинт @Mihinator3000 кажется валидным. Возможно, нам нет смысла натягивать абстракции друг на друга. Мы можем ввести интерфейc, который будет предоставлять метода вида AddCourseToPointsUpdate и его прокидывать во все хендлеры, чтобы хендлеры даже и не знали, что их баллы IGoogleTableAccessor будет обрабатывать.

Но ещё больше соглашусь с @ronimizy, что лучше завести ишую и описать предложение. Было бы круто добить этот PR до выходных, чтобы на синке что-то можно было обсудить дальше.

2022-08-19 06:04 UTC, ronimizy approved these changes

2022-08-19 06:35 UTC, FrediKats approved these changes
Я так понимаю, уже не драфт?

2022-08-19 16:24 UTC, FrediKats commented
Всё зелёное. Мёрджим?

2022-08-19 16:25 UTC, Mihinator3000 commented
Щас я очередь прикручу и можно, вообще было бы неплохо если б вы глянули че я тут добавил

2022-08-19 18:12 UTC, ronimizy requested changes

2022-08-19 18:12 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Dto/Google/TableCourseDto.cs
> +public record TableInfoDto(string Title, string? SpreadsheetId);
Увидел, ладно пусть будет название без айдишника. Но, всё-таки мне кажется что это вот как дто не нужно. Дто нужно чтобы что-то отдавать из презентейшена по большей части, тут можно, и даже наверное лучше будет, "заинлайнить" эти данные в респонс, это уберёт лишний тип используемый литерали только для того чтобы передать данные в респонсе, и даст возможность сделать декнострукт сразу при авейте)

2022-08-19 18:12 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Тут оно всегда будет нал, ты ещё раз кверю не выполняешь, оно само там не появится.

2022-08-19 18:12 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +            var query = new AddGoogleTableSubjectCourseAssociation.Query(subjectCourseId, spreadsheetId);
Только сейчас заметил. `Add` и `Query`? Если запрос не только читает данные, но ещё и как-то их изменяет, то это `Command`

2022-08-19 18:12 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessorWorker.cs
> +            await Task.WhenAll(pointsUpdateTasks.Union(queueUpdateTasks));
Ну тут у тебя гарантировано пересечений не будет, зато оно попытается сравнивать таски, лучшею зай `Concat`

2022-08-19 18:31 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
ОЙ ОЙ ОЙ, опять отдаёшь доменные сущности в респонсе. Думал я не замечу?)

2022-08-19 18:45 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessorWorker.cs
> +}
Меня просто не сильно радует в таком случае двойное использование слова queue

2022-08-19 18:45 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
> ОЙ ОЙ ОЙ, опять отдаёшь доменные сущности в респонсе. Думал я не замечу?)

Это где?)

2022-08-19 18:49 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Да, чет протупил

2022-08-19 19:00 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Да, чет протупил

2022-08-19 19:07 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
> Это где?)

Ну посмотри дефинишен StudentQueue

2022-08-19 19:07 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Да, чет протупил

2022-08-19 19:08 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Да харе тупить…

2022-08-19 19:09 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
Ебать, это так у меня интернет глючнул? Удобненько

2022-08-19 19:10 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        }
)

2022-08-19 19:11 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
Это рофл надеюсь?)

2022-08-19 19:16 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Study/SubjectCourse.cs
> +    public virtual string Name { get; protected init; }
кста, для LazyProxies не обязательно делать все свойства виртуальными, нужны только виртуальные навигационные свойства

2022-08-19 19:24 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
Нет не рофл. У тебя там коллекция доменных сущностей, то что ты её обернул в структуру ничего не меняет. Делай дто.

2022-08-19 19:25 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
А в чем тогда разница с CoursePoints? Я могу там тоже все под дто сделать

2022-08-19 19:26 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
Разница в том, что я раньше туда не смотрел, ну или смотрел и проглядел)
Конечно надо и там дто отдавать.

2022-08-19 19:26 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessorWorker.cs
> +}
Может хоть что-то типа ITableUpdateQueue?

2022-08-19 19:27 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/Queries/GetStudentsQueueBySubjectCourse.cs
> +    public record Response(StudentsQueue Queue);
Ок. Я буквально сверху спрашивал про CoursePoints..

2022-08-19 19:28 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessorWorker.cs
> +}
А что меняется? Я ведь так понял что проблема как раз с неймингом методов

2022-08-19 19:28 UTC, Mihinator3000 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessorWorker.cs
> +}
Ну мы не курс обновляем, как в твоем примере, но чтобы с неймингом методов проблем не было, я еще не придумал

2022-08-19 19:33 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessorWorker.cs
> +}
Ну я в имя интерфейса Course вынес чтобы убрать его дублирование в именах метода. 
Кмк Enqueue и Queue через одно слово не особо проблема, в любом случае можно потом заренеймить. Просто воркер в имени интерфейса это ну чёт прям совсем плохо.

2022-08-19 19:41 UTC, Mihinator3000 commented
Я тут еще заметил, что у всех созданных таблиц остается первоначальный лист Sheet1, выглядит не оч красиво, с ним надо что-то делать?

2022-08-19 19:46 UTC, ronimizy commented
> Я тут еще заметил, что у всех созданных таблиц остается первоначальный лист Sheet1, выглядит не оч красиво, с ним надо что-то делать?

Думаю на этом этапе можно забить и руками потом его удалить, пока что есть более важные вопросы.

2022-08-19 19:53 UTC, ronimizy approved these changes
АСТАНАВИТЕСЬ! Хватить аннотировать каждый тип!

2022-08-19 19:53 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        (_, string? spreadsheetId) = await _mediator.Send(getTableInfoQuery, token);
```suggestion
        var (_, spreadsheetId) = await _mediator.Send(getTableInfoQuery, token);
```

2022-08-19 19:53 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/GoogleTableAccessor.cs
> +        (string subjectCourseName, spreadsheetId) = await _mediator.Send(getTableInfoQuery, token);
```suggestion
        (var subjectCourseName, spreadsheetId) = await _mediator.Send(getTableInfoQuery, token);
```

2022-08-19 20:14 UTC, merged