feat: implement syncing github admins with mentors
kysect/Shreks pull request #131
Opened 2022-08-20 18:10 UTC by FrediKats

Есть ряд сомнительных мест, так что лучше смотреть чем не смотреть.

2022-08-20 19:00 UTC, ronimizy requested changes

2022-08-20 19:00 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Kysect.Shreks.Application.Handlers.csproj
> +        <PackageReference Include="Octokit" Version="2.0.1" />
Ааааээээээ..... 
Не понял мува. От слова совсем.
У нас есть интегрейшн проект, в нем содержится логика работы с гх, хендлеры всё-таки про бизнес логику (как никак апликейшн). Давай всё-таки делать так же как есть сейчас, у нас, например, таблицы не строятся в хендлерах, сделай интерфейс в абстракциях приложения, реализуй в интеграции с гх, а в хендлере его вызови.

2022-08-21 07:57 UTC, ronimizy requested changes

2022-08-21 07:57 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/SyncGithubAdminWithMentorsHandler.cs
> +        return currentMentors.ToHashSet();
Зумеры не придумали Distinct?

2022-08-21 07:57 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/SyncGithubAdminWithMentorsHandler.cs
> +            .FirstOrDefaultAsync(cancellationToken);
Ты тут Where на проверку тега забыл.

2022-08-21 08:10 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/SyncGithubAdminWithMentorsHandler.cs
> +        return currentMentors.ToHashSet();
Я использовал HashSet т.к. мне единственное, что нужно от этой коллекции - проверять вхождения в неё.

2022-08-21 08:28 UTC, ronimizy approved these changes

2022-08-21 09:33 UTC, merged