feat: merge startup configs
kysect/Shreks pull request #158
Opened 2022-08-21 21:55 UTC by FrediKats

Повыносил из плейграундов всё то, что нужно было для запуска WebApi

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
```suggestion
        .AddGoogleIntegration(o => o
            .ConfigureGoogleCredentials(googleCredentials)
            .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
```

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
Вообще надо бы DriveId вынести в отдельную константу, и сделать мб драйв для тестов, я тут свой оставил случайно)

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .AddDatabaseContext(opt => opt
Можно наверное сделать `o` вместо `opt`, чтоб было единообразно, либо наоборот

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    public List<string> Users { get; init; }
Может все-таки добавить = null!; чтобы гх не ругался?

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +                .ConfigureEntityGenerator<Submission>(s => s.Count = 1000)
Тут какие-то методы остались сверху и дублируются по какой-то причине

2022-08-21 23:33 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    public List<string> Users { get; init; }
А вообще этот класс дублирует уже существующую в плейграунде, не оч понял зачем

2022-08-22 07:39 UTC, FrediKats commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +                .ConfigureEntityGenerator<Submission>(s => s.Count = 1000)
В мёрдж проиграл я.

2022-08-22 07:40 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    public List<string> Users { get; init; }
Дублирует т.к. веб апи не референсит плейграунд, а я не знал куда его вынести и просто сскопировал, чтобы оно хоть как-то завелось.

2022-08-22 07:43 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
А на что он влияет? Я когда запускал, оно создавало файлы на моём диске 🤔

2022-08-22 07:45 UTC, Mihinator3000 commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
Я переделал в #157 авторизацию, так что теперь влияет, в доке обновленная инфа. Теперь токены обновлять не надо будет

2022-08-22 07:55 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        .ConfigureDriveId("17CfXw__b4nnPp7VEEgWGe-N8VptaL1hP"));
А, точно, я же без этого кода запускал. Затупил, сорри.

2022-08-22 10:22 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    public List<string> Users { get; init; }
Думаю, мы потом придумаем что-то более адекватное. Это временное решение для демки.

2022-08-22 10:38 UTC, darksidersstrife requested changes

2022-08-22 10:38 UTC, darksidersstrife commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    User first = users[0];
А если нам нескольких надо добавить...

2022-08-22 20:39 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    User first = users[0];
Надеюсь, ты доволен.

2022-08-22 21:12 UTC, FrediKats commented
Мы обязательно учтём твои пожелания, Сонар, но в следующей версии.

2022-08-22 21:36 UTC, merged