feat: add help command
kysect/Shreks pull request #167
Opened 2022-08-22 23:55 UTC by FrediKats

close #163

2022-08-22 23:57 UTC, annchous requested changes

2022-08-22 23:57 UTC, annchous commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/HelpCommand.cs
> +- `/to-draft` - перевод сабмишена в не активное состояние, чтобы обозначить, что он не готов к сдаче
```suggestion
- `/to-draft` - перевод сабмишена в неактивное состояние, чтобы обозначить, что он не готов к сдаче
```

2022-08-23 00:00 UTC, hrrrrustic approved these changes

2022-08-23 00:00 UTC, hrrrrustic commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs
> +                        if (!string.IsNullOrEmpty(result.Message))
На WhiteSpace бы еще проверять!

2022-08-23 19:51 UTC, hrrrrustic commented
уъу конфликты

2022-08-23 20:19 UTC, annchous approved these changes

2022-08-23 20:22 UTC, merged