GitHub user authorization
kysect/Shreks pull request #187
Opened 2022-08-24 19:45 UTC by annchous

Close #69 

Надо будет потом подумать, возможно ли и как сделать двойную авторизацию: сначала в ITMO ID, потом в GitHub (нужно ли как-то сохранить результат первого запроса (клеймы) перед вторым?).

Ну и сейчас второй метод в апишке будет падать, так как в базе не найдётся юзера с id NewGuid. Собственно, ждём авторизацию от ИТМО, чтоб полноценно протестировать.

2022-08-24 19:46 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +    public async Task<IActionResult> UpdateAuthorizedUserGithubUsername()
Чёт помучалась с названием этого метода, и ничего особо хорошего не вымучала.

2022-08-24 19:47 UTC, annchous commented
За секретами обращайтесь в личку https://t.me/annchouss

2022-08-24 19:49 UTC, FrediKats commented
Не забудь в ишуе на итмо ид отписать, что нужно прокидывать это всё в таком поряядке.

2022-08-24 19:54 UTC, FrediKats requested changes

2022-08-24 19:54 UTC, FrediKats commented on Source/Domain/Kysect.Shreks.Core/Users/User.cs
> +    public User(string firstName, string middleName, string lastName, string githubUsername)
У юзера гитхаб юзернейм хранится ассоциацией. Их создавать нужно отдельно. Вот пример того, как мы тестовые генерим - https://github.com/kysect/Shreks/blob/master/Source/Kysect.Shreks.WebApi/Program.cs#L127-L131

2022-08-24 19:54 UTC, FrediKats commented on Source/Kysect.Shreks.WebApi/Program.cs
> +        });
Закинь это в https://github.com/kysect/Shreks/blob/master/Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs

Желательно отдельный приватный метод AddGhAuth, который вызывается в общем методе AddGithubServices.

2022-08-24 20:08 UTC, annchous commented on Source/Domain/Kysect.Shreks.Core/Users/User.cs
> +    public User(string firstName, string middleName, string lastName, string githubUsername)
Спасибо, не знала.

2022-08-24 20:42 UTC, xrem commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +        services.AddAuthentication(options =>
Если планируется несколько "авторизаций" то стоит регистрировать как дефолтную схему некий композитный вариант, внутри которого уже набор клеймов, но это так, чисто мысли вслух.

После этого PR'a при добавлении на контроллеры [Authorize] аттрибута будет использоваться именно требоваться именно авторизация через GitHub

2022-08-24 20:58 UTC, xrem commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +                if (context.AccessToken is { })
```suggestion
                if (context.AccessToken is not null)
```

2022-08-24 20:58 UTC, xrem commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +            return BadRequest();
```suggestion
            return Unauthorized();
```

2022-08-24 20:58 UTC, xrem commented on Source/Kysect.Shreks.WebApi/Kysect.Shreks.WebApi.csproj
> +    <UserSecretsId>dcb623c6-ceae-4ac4-9f2c-a7bfc6535dcb</UserSecretsId>
Как будто это нужно в какой-нибудь конфиг

2022-08-24 20:58 UTC, xrem commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +        String? githubUsername = userClaims
```suggestion
        string? githubUsername = userClaims
```

2022-08-24 20:58 UTC, xrem commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +            .LastOrDefault();
И да, у тебя ж вроде есть Claim с именем, зачем какие-то махинации с урлом делать?
https://github.com/kysect/Shreks/blob/1ae72a55337d8164eb851315298293d5127f61b9/Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs#L110

2022-08-24 21:00 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +            .LastOrDefault();
Потому что имя != юзернейм. У меня вот имя Annchous, а юзернейм annchous.

2022-08-24 21:01 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Kysect.Shreks.WebApi.csproj
> +    <UserSecretsId>dcb623c6-ceae-4ac4-9f2c-a7bfc6535dcb</UserSecretsId>
Хм, а почему? Это ведь какая-то внутрянка дотнета, которая потом позволяет секреты доставать и т.д.

2022-08-24 21:02 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Kysect.Shreks.WebApi.csproj
> +    <UserSecretsId>dcb623c6-ceae-4ac4-9f2c-a7bfc6535dcb</UserSecretsId>
Если что, то значение - это произвольный гуид, не имеющий отношения к самим секретам.

2022-08-24 21:02 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Controllers/GithubAuthController.cs
> +            return BadRequest();
Упс, тут вообще забыла поправить. Спасибо!

2022-08-24 21:05 UTC, annchous commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +        services.AddAuthentication(options =>
Звучит страшно...

2022-08-24 21:13 UTC, annchous commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +        services.AddAuthentication(options =>
Это то, о чём ты говоришь? https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-6.0#use-multiple-authentication-schemes

2022-08-24 21:29 UTC, ronimizy commented
А разве мы на синках не обсуждали, что аутентификация у нас именно через итмо ид, гх мы подтягиваем как интеграцию? 🤔

2022-08-25 05:45 UTC, Bibletoon reviewed
Остальное вроде ок

2022-08-25 05:45 UTC, Bibletoon commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    app.UseStaticFiles();
А зачем это в рамках данного пра?

2022-08-25 05:45 UTC, Bibletoon commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubConfiguration.cs
> +    public string? OAuthClientSecret { get; set; }
Стоит добавить пустые поля в appsettings.json, чтобы можно было не гадать по коду какие поля нужно докинуть в конфиг для запуска

2022-08-25 08:49 UTC, annchous commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubConfiguration.cs
> +    public string? OAuthClientSecret { get; set; }
Ну вообще я добавляю секреты не через appsettings, а через dotnet user-secrets команду.

2022-08-25 08:49 UTC, annchous commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Helpers/GithubConfiguration.cs
> +    public string? OAuthClientSecret { get; set; }
То есть они у тебя нигде светиться не будут. И плюс этого - невозможно случайно закоммитить эти секреты на гх.

2022-08-25 08:50 UTC, annchous commented on Source/Kysect.Shreks.WebApi/Program.cs
> +    app.UseStaticFiles();
Уф, ну просто чтоб потом не забыть)0
Если критично, могу убрать )

2022-08-25 08:53 UTC, annchous commented
> А разве мы на синках не обсуждали, что аутентификация у нас именно через итмо ид,а гх мы подтягиваем как интеграцию? 🤔

Что это значит? У нас есть сценарий, когда мы авторизовываем пользователя (студента) через ITMO ID - тут мы создаём студента. А затем нам надо положить в базу информацию о гитхабе этого пользователя - и делаем мы это как раз путём авторизации? Что значит "подтягиваем как интеграцию"?

cc: @ronimizy

2022-08-25 08:57 UTC, ronimizy commented
Подтягиваем как интеграцию, значит что студент аутентифицируется через ITMO ID, далее заходит в "личный кабинет" и нажимает кнопку "привязать гх". 

Энивей ИТМО ид сейчас выглядит как то, что должно быть основным сурсом авторизации, а насчёт того чтобы делать два сурса сейчас я хз, кажется что это не особо нужно. Мб @FrediKats поправит…

2022-08-25 09:54 UTC, annchous commented
> Подтягиваем как интеграцию, значит что студент аутентифицируется через ITMO ID, далее заходит в "личный кабинет" и нажимает кнопку "привязать гх".
> 
> Энивей ИТМО ид сейчас выглядит как то, что должно быть основным сурсом авторизации, а насчёт того чтобы делать два сурса сейчас я хз, кажется что это не особо нужно. Мб @FrediKats поправит…

Ну, не знаю... Это потребует от студента больше действий, чем нажать две рядом стоящие кнопки. Ну и тема с тем, что может не каждый хочет привязывать туда гитхаб и т.д.

@FrediKats your opinion?

2022-08-25 10:03 UTC, annchous commented
С другой стороны это решает проблему "двух авторизаций" (насколько это возможно и как сложно настраивать). Но вы уверены, что ITMO ID выдаст информацию о привязанных профилях?

2022-08-25 10:21 UTC, ronimizy commented
> С другой стороны это решает проблему "двух авторизаций" (насколько это возможно и как сложно настраивать). Но вы уверены, что ITMO ID выдаст информацию о привязанных профилях?

А нам от него что-то нужно кроме табельного студента? Группу вроде как решили через my Itmo получать

2022-08-25 16:02 UTC, FrediKats commented
Такс, кажется тут мискоммуникация какая-то.

Для начала ещё раз проговорю воркфлоу:

1. Студент заходит на в наш недо UI, тыкает на кнопку авторизации через ITMO ID
2. Переходит на ITMO ID, вводит креды, получает результат
3. После этого он также тыкает на кнопку авторизации через Github, вводит креды, получает результат
4. Система после получения данных о ITMO ID создаёт пользователя, а после получния Github - привязывает ассоциацию

На этом всё, история UI заканчивается. А теперь QnA.

> Q: далее заходит в "личный кабинет" и нажимает кнопку "привязать гх".

Если речь про личный кабинет" от ИТМО, то там такой возможности нет. Если речь про наш "личный кабинет", то... Ну, это он и есть - вот вам две кнопки. Не вижу смысла тратить время на оформление страницы, куда нужно зайти один раз и тыкнуть две кнопки.

> Группу вроде как решили через my Itmo получать

Такс, пажжи) Мы вообще вроде не говорили про My itmo. А если и говорил я, то видимо подразумевая ITMO ID. У нас же вообще никакого доступа к my itmo нет. Всё что мы будем получать - это данные после авторизации в ITMO ID.

2022-08-25 16:20 UTC, ronimizy commented
В том воркфлоу что ты описал, тыкание кнопки гх не тыкнув ИТМО ид - не имеет смысла. Так что всё-таки это больше похоже на ту модель что я описывал, мы аутентифицируем через ИТМО ид, а потом привязываем гх.

Смысл делать два вида аутентификации сейчас?

2022-08-25 17:09 UTC, annchous commented
> В том воркфлоу что ты описал, тыкание кнопки гх не тыкнув ИТМО ид - не имеет смысла. Так что всё-таки это больше похоже на ту модель что я описывал, мы аутентифицируем через ИТМО ид, а потом привязываем гх.
> 
> Смысл делать два вида аутентификации сейчас?

Ну мы можем не давать авторизоваться в гх, если ещё не получены данные от ИТМО.

2022-08-25 17:13 UTC, ronimizy commented
Я не предлагаю писать Мега-Гига-Супер-UI для личного кабинета. Суть в том, что аутентификация через гх нам не нужна.

Три вьюшки: одна с кнопкой зайти через ИТМО ид, одна с кнопкой привязать гх, и третья которая смотрит наличие токена ИТМО ид и по этому признаку редиректит либо на первую, либо на вторую. 
^ этот UI реализовать супер просто.

2022-08-25 17:14 UTC, FrediKats commented
> а потом привязываем гх.

Это уже, скорее, вопрос терминологии. Пользователь заходит в ITMO ID. А потом заходит в Github, чтобы связать его с тем, что было в ITMO ID. Я это описывал и в ишуе и в коменте выше. Мы не делаем независимую авторизацию через GH. Всё что от неё будет использовано - это получение username.

2022-08-25 17:38 UTC, ronimizy commented
У меня всё ещё есть ощущение, что в плане аутентификации, мы делаем что-то совсем не то... Но whatever...

2022-08-25 18:24 UTC, FrediKats commented
Нам сейчас главное сделать какие-то шаги и наработки в сторону авторизации. А потом, когда отдельные части будут готовы, сесть и посмотреть как лучше скомпоновать это всё. Это же не значит, что мы в таком виде сейчас всё оставим и выкатим в прод.

2022-08-25 19:30 UTC, annchous commented
Таки что с пулл-реквестом теперь делать?)

2022-08-25 19:52 UTC, FrediKats approved these changes
С гитхабом всё ок, в рамках доработки по ITMO ID будем думать, как его скрестить.

2022-08-25 19:54 UTC, merged