Feat/submission state commands
kysect/Shreks pull request #189
Opened 2022-08-24 20:39 UTC by ronimizy

- closes #177

2022-08-24 21:14 UTC, FrediKats requested changes
А зачем SubmissionStateHandlerBase и три реализации? Они же отличаются только одним аргументом? Почему просто из юзер команд не прокинуть этот енам? Мне кажется, что это на ровном месте усложняет решение и превращает его из "изменить значение енама" на какие-то хендлеры, которые друг друга дублируют.

2022-08-24 21:14 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(false, $"Received error while process update command: {e}");
> process update command

2022-08-24 21:26 UTC, ronimizy commented
Ну можно и так в принципе

2022-08-25 16:12 UTC, FrediKats approved these changes
Я пока не знаю, когда у нас должны ставится invalid state'ы, но в остальном всё круто.

2022-08-25 16:43 UTC, ronimizy commented
> Я пока не знаю, когда у нас должны ставится invalid state'ы, но в остальном всё круто.

Когда CI падает, обсуждали же в дискорде

2022-08-25 16:44 UTC, merged