Feat/seeding infrastructure
kysect/Shreks pull request #20
Opened 2022-07-17 18:59 UTC by ronimizy

closes #19

2022-07-17 19:03 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
> +            .AreNotInterfaces();
Вот она, та фича) 

--> [docs](https://github.com/ronimizy/FluentScanning/blob/main/README.md#registration-as-type-constructed-from-given-type) <--

2022-07-17 23:31 UTC, darksidersstrife approved these changes
lgtm

2022-07-18 04:46 UTC, FrediKats requested changes

2022-07-18 04:46 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/Options/EntityGenerationOptions.cs
> +    }
Что это за метод, что он делает?

2022-07-18 04:46 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/IAssemblyMarker.cs
> +public interface IAssemblyMarker { }
Теперь в двух проектах два интерфейса с одинаковыми названиями?

2022-07-18 04:46 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
> +            .AreNotInterfaces();
Ни из описания, ни из юзаджа до конца не понял, какую проблему мы решали. Это поддержка регистраций DI, когда в качестве базового типа используется интерфейс с дженериком? А раньше можно было только явные типы вставить?

2022-07-18 04:46 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/EntityGeneratorBase.cs
> +        => Generate(0);
Кажется, нужно таки что-то решить с кодстайлом) У тебя строкой выше на одной линии, а тут перенос.

2022-07-18 05:27 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/EntityGeneratorBase.cs
> +        => Generate(0);
Захватил бы комментом сразу оба кейса, а то оч понятно о чем это. 
Сверху - свойство, тут метод. 
Single line свойства - без переноса, single line метод - с переносом.

2022-07-18 05:28 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Options/EntityGenerationOptions.cs
> +    }
Этот метод, через options паттерн, добавляет в коллекцию конфигурацию генерации конкретной сущности.

2022-07-18 05:30 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/IAssemblyMarker.cs
> +public interface IAssemblyMarker { }
Ну, да…
Это чисто метка, не думаю что это - проблема. Вот если бы такое было с интерфейсами, используемыми в бизнес логике, то да, повод задуматься.

2022-07-18 05:40 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
> +            .AreNotInterfaces();
Проблема такая. 
У нас женерик интерфейс:
```cs
interface IGeneric<T> { }
```

И несколько не женерик реализаций:
```cs
class IntConcrete : IGeneric<int> { }

....
```

Нам нужно найти все типы, реализующие этот интерфейс, и зарегестрировать их в коллекции как реализации этого интерфейса с соответствующим типом-аргументом. 

В прошлой версии либы, этих методов не было, была лишь проверка на `AssignableTo`, что в данном случае, по очевидным причинам, будет выдавать нам `false`.

2022-07-18 05:42 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/EntityGeneratorBase.cs
> +        => Generate(0);
Блин, вроде выделял всё, сорри.

А почему для метода не на той же строке?

2022-07-18 05:44 UTC, FrediKats commented on Source/Infrastructure/Kysect.Shreks.Seeding/IAssemblyMarker.cs
> +public interface IAssemblyMarker { }
Ну, я скорее о том, что коллизии. Понимаю, что метка, но может им разные имена развесить, чтобы случайно не проиграть в юзингах потом? Не тот интерфейс заюзал и всё, иди дебаж почему сидинг не отработал)

2022-07-18 05:46 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/EntityGeneratorBase.cs
> +        => Generate(0);
По моему опыту, single line вызовы у свойств - довольно короткие, тогда как у методов могут быть не очень короткими. То есть, не настолько длинными чтобы выносить аргументы на разные строки, но на столько, что правила форматирования переносят его на другую строку. Поэтому, чтобы везде одинаково было, методы сразу на другой строке.

2022-07-18 05:52 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/IAssemblyMarker.cs
> +public interface IAssemblyMarker { }
Звучит. Можно таску на рефактор завести, чтобы сразу все поменять и не смешивать скоуп изменений.

2022-07-18 06:06 UTC, Bibletoon commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
> +        collection.AddSingleton(typeof(EntityGeneratorOptions<>));
А зачем?

2022-07-18 06:09 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/RegistrationExtensions.cs
> +        collection.AddSingleton(typeof(EntityGeneratorOptions<>));
Чтобы можно было не регать конфигурации для всех сущностей, а для некоторых юзать дефолтную.

2022-07-18 06:20 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/IAssemblyMarker.cs
> +public interface IAssemblyMarker { }
Добавил 
- #23

2022-07-18 06:54 UTC, FrediKats approved these changes

2022-07-18 06:55 UTC, merged