feat: handle submission by another student correctly
kysect/Shreks pull request #211
Opened 2022-08-26 22:24 UTC by olefirenque

2022-08-26 22:33 UTC, FrediKats requested changes

2022-08-26 22:33 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +                var message = $"Repository {repository} is assigned to another student. Close this pull request";
Вместо "Close this pull request" стоит добавить, что "User {sender} does not have permission here. Close this PR and open new with correct account."

2022-08-26 22:33 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +                var message = $"Repository {repository} is assigned to another student";
+ "Do not user {sender} account for this repository. Submission date will be update."

2022-08-26 22:48 UTC, FrediKats approved these changes

2022-08-26 22:52 UTC, annchous commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +        bool triggeredByAnotherUser = !string.Equals(repository, sender, StringComparison.CurrentCultureIgnoreCase);
А почему тут имя репозитория сравнивается с именем польователя? Или я не так поняла?

2022-08-26 22:54 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +        bool triggeredByAnotherUser = !string.Equals(repository, sender, StringComparison.CurrentCultureIgnoreCase);
У нас дизайн системы предполагает, что у всех студентов их репо называется также, как и их юзернейм.

2022-08-26 22:54 UTC, annchous commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +        bool triggeredByAnotherUser = !string.Equals(repository, sender, StringComparison.CurrentCultureIgnoreCase);
Может тогда сделать тут var repositoryOwnerName?

2022-08-26 22:57 UTC, annchous commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +                throw new DomainInvalidOperationException(message);
Пробельчика между строками не хватает. :c

2022-08-26 22:58 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +        bool triggeredByAnotherUser = !string.Equals(repository, sender, StringComparison.CurrentCultureIgnoreCase);
Я бы даже предложил сделать отдельный осознанный класс в .Core, который бы инкапсулировал логику. И можно заодно туда /// summary написать, что оно вот так и это бай дизайн.

2022-08-26 22:59 UTC, annchous commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/CreateOrUpdateGithubSubmissionHandler.cs
> +                throw new DomainInvalidOperationException(message);
Пробэльчик бы.

2022-08-27 18:03 UTC, FrediKats commented
@olefirenque можешь мастер себе вмёрджить и докинуть сюда - https://github.com/kysect/Shreks/blob/master/Source/Application/Kysect.Shreks.Application.Handlers/Validators/PermissionValidator.cs

2022-08-28 19:04 UTC, merged