feat: generate repo from template for invited
kysect/Shreks pull request #218
Opened 2022-08-27 17:40 UTC by Kerenery

2022-08-27 17:50 UTC, FrediKats requested changes

2022-08-27 17:50 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +        foreach (var addedUser in inviteResult.AlreadyAdded)
Это всё лучше вынести в отдельный метод.

2022-08-27 17:50 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +                                         $"No template repository found for organization {organizationName}");
Вытаскиваются все репо N раз. Можно перед  foreach вытащить один раз.

2022-08-27 17:50 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +                ?? await client.Repository.Generate(
Я бы всё ещё предложил использовать if вместо ?? для сложных конструкций. И логировать, что для юзера создан репо.

2022-08-30 13:18 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +            if (userRepository is not null) continue;
На новую строчку бы

2022-08-30 13:18 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +                });
Мб в отдельную переменную?

2022-08-30 13:18 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +                                            $"No template repository found for organization {organizationName}");
Я бы тут скорее сделал if и мессадж эксепшена в отдельную переменную

2022-08-30 13:18 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +            var userRepository = repositories.FirstOrDefault(repository => repository.Name == addedUser);
Тут в linq параметр называется repository, выше просто repo, мне кажется должно быть однообразно, я `r` или просто `x` порекомендовал бы

2022-08-30 16:55 UTC, FrediKats requested changes
А мы вроде обсуждали, что после создания нужно пользователю дать права на это репо. Не вижу этого в коде.

2022-08-30 16:55 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +            var userRepository = repositories.FirstOrDefault(repository => repository.Name == addedUser);
И сравнивать лучше с IgnoreCase. На всяк случай.

2022-08-30 19:02 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +            throw new InfrastructureInvalidOperationException(string.Format(missingRepoException, organizationName));
Вообще я имел в виду что-то типа:

```suggestion
        if (templateRepository is null)
        {
            string message = $"No template repository found for organization {organizationName}";
            throw new InfrastructureInvalidOperationException(message);
```

2022-08-30 19:02 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +        foreach (var addedUser in inviteResult.AlreadyAdded)
Если addedUser это юзернейм, то мб его так и назвать?

2022-08-30 19:04 UTC, Kerenery commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +        foreach (var addedUser in inviteResult.AlreadyAdded)
да, а то addedUser как сущность звучит

2022-08-30 21:03 UTC, FrediKats approved these changes
В целом ок.

2022-08-30 21:03 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Invites/GithubInvitingWorker.cs
> +            throw new InfrastructureInvalidOperationException(message);
LogError + skip. Не стоит бросать эксепшен.

2022-09-01 17:01 UTC, FrediKats commented
У нас в итоге появился кейс, когда нужно на не темплейт смотреть, так что я побыстрому прикрутил фильтр по этому.

2022-09-01 17:18 UTC, merged