Feat/webhooks handling
kysect/Shreks pull request #22
Opened 2022-07-17 21:32 UTC by lipa44

# Issues

* closes #1 
* closes #18  

# Comments

1. У нас есть **файл** с `secretKey` для `GitHubApp` - надо решить, будем ли мы его пушить в гит или локально будет перекидывать друг другу
2. Пока что стоит вопрос с инжектом кастомного CredentialStore для того, чтобы в нём реализовать логику пересоздания токена (альтернативой является просто выставление Sroped лайфтайма у клиента, которому надо менять токены)

2022-07-17 21:38 UTC, lipa44 commented
По приколу закину скрин того, как выглядит хендлинг

<img width="792" alt="image" src="https://user-images.githubusercontent.com/82240296/179425737-bf96c1fe-1959-4e1d-bc2f-4c55c3cb7bf8.png">

2022-07-17 21:43 UTC, lipa44 commented
Пока что не представляю себе, как можно будет привести хендлеры к созданным абстракциям _(тк весь функционал наследуется от либы гх, я там ничего не могу переопределить и привести к нашим абстракциям)_. Разве что сделать уродский фасад...

2022-07-17 22:33 UTC, darksidersstrife commented
> Пока что не представляю себе, как можно будет привести хендлеры к созданным абстракциям
Не совсем понял

2022-07-17 22:36 UTC, lipa44 commented
> > Пока что не представляю себе, как можно будет привести хендлеры к созданным абстракциям
> 
> Не совсем понял

Фреди в темплейтн проекта сделал абстракции `IGithubActivityHandler` и т.п. - от них оч сложно наследоваться, потому что я не имею доступа к изменению аргументов хендлера, а все их аргументы являются внутренними классами Oktokit

2022-07-17 22:43 UTC, darksidersstrife reviewed
> У нас есть файл с secretKey для GitHubApp - надо решить, будем ли мы его пушить в гит или локально будет перекидывать друг другу

Точно не надо его пушить в репо)
Пока что стоит вопрос с инжектом кастомного CredentialStore для того, чтобы в нём реализовать логику пересоздания токена (альтернативой является просто выставление Sroped лайфтайма у клиента, которому надо менять токены)

Давай все же так и сделаем, а то получается на каждый запрос будет выделяться процессор, два клиента...
Подсчитыватель аллокаций во мне не годует
Там 20 строчек написать)

2022-07-17 22:43 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<WebhookEventProcessor, CustomWebhookEventProcessor>();
Так это и на каждый запрос свой процессор будет создаваться :thinking:

Ну это как-то неоч

2022-07-17 22:45 UTC, darksidersstrife commented
> Фреди в темплейте проекта сделал абстракции IGithubActivityHandler и т.п.
А, да они не нужны
)

2022-07-17 22:47 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<WebhookEventProcessor, CustomWebhookEventProcessor>();
Ну да. Пока что драфт, поэтому ок))

Попробую переписать на кастомный `CredentialStore`.

2022-07-17 23:30 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<WebhookEventProcessor, CustomWebhookEventProcessor>();
> Там 20 строчек написать)
Ладно, на самом деле там неплохо бы синхронизацию сделать при обновлении токена, чтобы одновременно несколько запросов не пошли, но это ладно

2022-07-18 08:38 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<WebhookEventProcessor, CustomWebhookEventProcessor>();
> > Там 20 строчек написать)
> 
> Ладно, на самом деле не совсем просто - там неплохо бы синхронизацию сделать при обновлении токена, чтобы одновременно несколько запросов не пошли, но это ладно

Ладно синхронизацию, тебе надо быть увереным в том, что у тебя системя расширится на >1 юзера (то есть тебе надо продумать момент с тем, чтобы левый юзер не получил не свой токен) - это главная проблема, которая меня в этом плане стопит. Я не совсем понимаю, как это правильно сделать

2022-07-18 11:47 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +
А в чем смысл использовать андескор для названия параметра, который мы используем?

2022-07-18 13:20 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +        services.AddScoped<WebhookEventProcessor, CustomWebhookEventProcessor>();
Да, тут согласен, что процессор-то один, а хуки в него будут прилетать с разных инсталляций
Ну тогда installation клиент пересоздаем, плак
Ладно, проблем от этого быть не должно

2022-07-18 13:59 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +
Ну потому что там лежит всего 1 параметр `implementationFactory` и мне поидее не важно, что и это и как - мне надо просто достать оттуда зареганный сервис. Лишние буквы для этого писать не очень хотелось)

2022-07-18 14:02 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/IntegrationCredentialStore.cs
> +        }
ой как хорошо.........

2022-07-18 14:12 UTC, lipa44 reviewed
А ты уверен что оно работает?.....

2022-07-18 14:52 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +
Ну ок, я просто привык, что `_` используют как дискард, показывая, что параметр не используется дальше

2022-07-18 14:57 UTC, lipa44 commented
> Ну, добавь меня в свое репо админом, я проверю

А я пару дней назад тебе кидал инвайт уже

2022-07-18 14:57 UTC, lipa44 commented
> > Ну, добавь меня в свое репо админом, я проверю
> 
> А я пару дней назад тебе кидал инвайт уже 

Ток тебе надо передать секретный файл через секретный канал

2022-07-19 04:41 UTC, hrrrrustic commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Thread.VolatileWrite(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
У треда эти методы скоро задеприкейтят, лучше использовать сразу через класс Volatile (там такие же методы)

2022-07-19 04:41 UTC, hrrrrustic commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Thread.VolatileWrite(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
А зачем тут кстати Volatile вообще :thinking:

2022-07-19 11:24 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Thread.VolatileWrite(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
Чтобы не было гонок с чтением в проверке ниже (запись же асинхронно идет)

2022-07-19 11:54 UTC, darksidersstrife commented
Пока просто сеттим креды при создании, кредстор с рефрешем пусть останется, если вдруг понадобится в будущем

2022-07-19 13:16 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Thread.VolatileWrite(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
Деда приступ хватит, если он такое увидит

Тут классический дабл чек с локом, как при статической инициализации чего-нибудь, но сама инициализация асинхронно идет

То есть первая проверка идет чисто с volatile, чтобы не лочить на каждый запрос
Если нам такт надо рефрешить, то лок (всем надо подождать, пока запустится рефреш) 
Внутри пытаемся касом поставить, что мы начали создание таски на рефреш (только если еще не начали) 
После создания опять же касом ставим, что рефреш начался (к этому моменту он мог уже зафейлиться и в асинке бы выставилось в not refreshing)

2022-07-19 15:28 UTC, lipa44 commented
> Пока просто сеттим креды при создании, кредстор с рефрешем пусть останется, если вдруг понадобится в будущем

`.Result` выглядел очень больно, я его убрал

2022-07-19 15:40 UTC, lipa44 commented
А можно вопрос.

Ты убрал инжект CitHubClient, и прокинул его в конструктор `CustomWebhookEventProcessor`. Что ты ожидаешь увидеть в значении `CitHubClient _installationClient` этого процессора?

2022-07-19 15:41 UTC, lipa44 commented
2. Зачем ты инжектишь `installationClient` в`CustomWebhookEventProcessor`? Ты так отрезаешь возможность работать с несколькими инсталляциями.

3. Оно перестало работать после этих изменений

2022-07-19 15:45 UTC, lipa44 commented
Теперь надо прокидывать в конструктор `InstallationClientFactory`, раз ты его зарегистрировал, и из него получать `installationClient` новый - что нас откатывает к изначальному варианту.

Можешь, конечно, реализовать хранение `ConcurrentDictionary<InstallationId, InstallationClient>`, но глобально мы не сильно отойдём от изначального варианта)

2022-07-19 15:50 UTC, darksidersstrife commented
Ты чет не то смотришь, там фабрика инжектится

2022-07-19 15:56 UTC, lipa44 commented
> Ты чет не то смотришь, там фабрика инжектится

Тем не менее
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/82240296/179795302-f23fc88e-1716-401c-bb2b-2355e29d5337.png">

2022-07-19 16:03 UTC, darksidersstrife commented
Так это что-то с приватным ключом
Файл на месте, контент правильный?

2022-07-19 16:10 UTC, darksidersstrife commented
А что в эксепшене-то пишут

2022-07-19 16:10 UTC, lipa44 commented
> А что в эксепшене-то пишут

скажи куда мне закинуть тебе файл с ключом - ты сам чекнешь

2022-07-19 16:16 UTC, darksidersstrife commented
Как же он не хочет просто открыть на один уровень больше в дебаггере) 

Да в том же дискордике можно скинуть
Только вебхук же на твой smee.io прилетать будет :thinking:

2022-07-19 21:40 UTC, lipa44 commented
TODO:

- Реализовать `CuncurrentDictionary` в фабрике клиентов для хранения пар айди/инсталейшнКлиент

P.S. завтра закоммичу

2022-07-20 05:47 UTC, FrediKats requested changes

2022-07-20 05:47 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/IInstallationClientFactory.cs
> +namespace Kysect.Shreks.GithubIntegration.client;
Почему client c маленькой?

2022-07-20 05:47 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        var accessToken = await _gitHubAppClient.GitHubApps.CreateInstallationToken(installationId);
А это можно/нужно кешировать? Чтобы повторный запрос не создавал ещё один?

2022-07-20 05:47 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Volatile.Write(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
Будьте же вы людьми, напишите обёртку типизированную над этим, чтобы можно было енамы без кастов в логике менять и таймспаны нормальные юзать.

2022-07-20 06:58 UTC, FrediKats requested changes

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +public sealed class CustomWebhookEventProcessor : WebhookEventProcessor
Почему Custom?

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        _logger.Log(LogLevel.Debug, $"{nameof(ProcessPullRequestWebhookAsync)}: {pullRequestEvent.GetType().Name}");
_logger.Debug(...)?

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +    private bool IsSenderBot(WebhookEvent webhookEvent) => webhookEvent.Sender?.Type == UserType.Bot;
А если Sender == null?

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        if (IsSenderBot(pullRequestReviewEvent)) return;
Мб в ифе под Verbose залогировать, что скипает ивент т.к. соо от бота?

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        }
if (!ShoudHandle(action))
{
  _logger.Verbose($"Action {aciton} should not be handled by {nameof(...)}");
 return;
}

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +            $"**Hook**: `{nameof(ProcessPullRequestWebhookAsync)}`\n" + $"**Action**: `{pullRequestReviewEvent.Action}`\n" + $"**Content**: `{pullRequestReviewEvent.Review.Body}`");
Вынести в сущность, инкапсулировать этот вызов, чтобы тут было что-то вида

_commentSender.NotifyAboutAction(...) или что-то такое

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        }
А, стоп, что. Свитч же ничего не делает.

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +            $"**Hook**: `{nameof(ProcessIssueCommentWebhookAsync)}`\n" + $"**Action**: `{issueCommentEvent.Action}`\n" + $"**Content**: `{issueCommentEvent.Comment.Body}`");
Аналогично.

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            _tokenRefreshState != (int)TokenRefreshState.Refreshing)
var shouldUpdateCredentials = ...
if (!shouldUpdateCredentials)
  return _task;

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +        _task = Task.FromResult<Credentials>(null!);
null! выглядит очень неприятно

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +                    if (Volatile.Read(ref _expirationUnixTimestamp) <= DateTimeOffset.Now.ToUnixTimeSeconds())
Дублируется, лучше вынести в метод.

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +    public Task<Credentials> GetCredentials()
Порядок методов Я бы сначала паблик, а потом приват написал.

2022-07-20 06:58 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +    private async Task<Credentials> GetTask()
CreateNewToken? Название не информативное.

2022-07-20 07:35 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +        _task = Task.FromResult<Credentials>(null!);
А что можно сюда положить, зная, что это никогда не вернется и это пустота?

2022-07-20 08:01 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        var accessToken = await _gitHubAppClient.GitHubApps.CreateInstallationToken(installationId);
Если вы это сделаете прокси оберткой, а не добавлением логики кеширования прямо сюда, то будет супер.

2022-07-20 08:18 UTC, Bibletoon commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +
> Лишние буквы для этого писать не очень хотелось

Лучше так, чем видеть вызовы методов у _. Это прям очень плохо выглядит

2022-07-20 08:42 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +        _task = Task.FromResult<Credentials>(null!);
Можно хранить `Task<Credential>?`

2022-07-20 09:28 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/CredentialStores/InstallationCredentialStore.cs
> +            Volatile.Write(ref _expirationUnixTimestamp, token.ExpiresAt.AddMinutes(-1).ToUnixTimeSeconds());
Были бы дезигнеры языка людьми и давали бы енамы использовать нормально(

2022-07-20 10:23 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +    private bool IsSenderBot(WebhookEvent webhookEvent) => webhookEvent.Sender?.Type == UserType.Bot;
В рамках рассматриваемых нами ивентов, сендер не будет нулом, тк все экшены (даже в перспективе), которые я себе представляю, отправляются от какого-то лица (будь то пуш коммита, запрос ресью, коммент или что-то ещё)

2022-07-20 10:25 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +    private bool IsSenderBot(WebhookEvent webhookEvent) => webhookEvent.Sender?.Type == UserType.Bot;
Я думал конечно о том, чтобы написать 

```csharp
private bool IsSenderBot(WebhookEvent webhookEvent) => webhookEvent.Sender is null || webhookEvent.Sender.Type == UserType.Bot;
```

но посчитал что таких ситуаций быть не должно

2022-07-20 10:26 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        if (IsSenderBot(pullRequestReviewEvent)) return;
Звучит неплохо

2022-07-20 10:27 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        }
> А, стоп, что. Свитч же ничего не делает.

Пока что да, это просто затравка на будущее, я как бы описал все типы экшенов, которые мы можем обрабатывать, чтобы было понимание наших возможностей

2022-07-20 10:28 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +            $"**Hook**: `{nameof(ProcessIssueCommentWebhookAsync)}`\n" + $"**Action**: `{issueCommentEvent.Action}`\n" + $"**Content**: `{issueCommentEvent.Comment.Body}`");
Это и предыдущее - валидно.

2022-07-20 22:35 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +        if (IsSenderBot(pullRequestReviewEvent)) return;
`Verbose` на нашёл, зато нашёл `Trace`

2022-07-20 22:38 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Processors/CustomWebhookEventProcessor.cs
> +    private bool IsSenderBot(WebhookEvent webhookEvent) => webhookEvent.Sender?.Type == UserType.Bot;
В целом, ладно, не будем надеяться на гитхаб и не будем обрабатывать хуки, где сендер нул.

2022-07-21 01:08 UTC, lipa44 commented
Любезно принимаю доёбы касательно реализации кеша!

2022-07-21 01:10 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/AppBuilderExtensions.cs
> +        var gitHubConf = shreksConfiguration.GithubConfiguration;
тут момент конечно спорный, надо ли было сюда это добавлять, если мы в конфигурации это проверили

есчо напишите - удалю))

2022-07-22 09:34 UTC, ronimizy reviewed
@lipa44 валидация конфигурации – вещь конечно полезная, но грамотная архитектура приложения – ещё лучше.
1. Вызов `Verify` не должен находиться в методе добавления сервисов
2. Вызов `Verify` не должен находиться в методе настройки сервисов
3. `ShreksConfiguration` не должен содержать логику по проверке дочерних конфигураций

Верным решением будет реализация своего `Verify` в каждой конфигурации и вызов их в общей. А вызов общей после того как ты забиндишь данные из конфигурации в объект.

И сделайте отдельный проект для тестирования работы этого всего. То что у вас `Integration` проект **ЗАПУСКАЕМЫЙ** это что-то чего быть не должно. Потому что у веб проекта в `.csproj` должна быть выбрана веб сдк, тогда и не надо было бы руками костылять добавление `appsettings.json` в конфигурацию.

2022-07-22 12:31 UTC, lipa44 commented
> Потому что у веб проекта в `.csproj` должна быть выбрана веб сдк, тогда и не надо было бы руками костылять добавление `appsettings.json` в конфигурацию.

??

2022-07-22 12:33 UTC, ronimizy commented
> > Потому что у веб проекта в `.csproj` должна быть выбрана веб сдк, тогда и не надо было бы руками костылять добавление `appsettings.json` в конфигурацию.
> 
> ??

Посмотри первые строчки проекта что ты сейчас создал и что был до этого

2022-07-22 12:34 UTC, lipa44 commented
> > > Потому что у веб проекта в `.csproj` должна быть выбрана веб сдк, тогда и не надо было бы руками костылять добавление `appsettings.json` в конфигурацию.
> > 
> > 
> > ??
> 
> Посмотри первые строчки проекта что ты сейчас создал и что был до этого

Да, я сейчас посмотрел, но это как-то не поспособствовало автоматическому определению appsettings.json файла в конфигурации

2022-07-22 12:38 UTC, ronimizy commented
Где ты проект создал.... Там же есть проект с тестами, проект с плейграундом, каким местом это – презентейшн? В презентейшене будет уже сама апи. Стоит чуть-чуть вдумываться в структуру проекта, а то она превратится в помойку.

2022-07-22 12:38 UTC, ronimizy commented
> Да, я сейчас посмотрел, но это как-то не поспособствовало автоматическому определению appsettings.json файла в конфигурации

Or did it?

![Screenshot 2022-07-22 at 15 38 22](https://user-images.githubusercontent.com/71693183/180440836-9fcf4c22-4f2d-4ba1-bc67-423475e2fd4a.png)

2022-07-22 12:39 UTC, lipa44 commented
> 

По-моему, помойкой является расположение хостов в папке тестов

2022-07-22 12:39 UTC, ronimizy commented
> По-моему, помойкой является расположение хостов в папке тестов

По-моему, этот проект – не хост, а тестовый хост.

2022-07-22 12:42 UTC, lipa44 commented
Я перекинул его в папку на ФС, можешь делать с расположением проектов что хочешь

2022-07-23 13:09 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        return new GitHubClient(new ProductHeaderValue($"Installation-{installationId}"))
Так а чего не с кредстором с рефрешем 🤔

2022-07-23 13:40 UTC, ronimizy commented
> Тем не менее, в моём понимании это явно не должно лежать в папке тест. Возможно стоит сделать солюшн папку для _тестовых_ **хостов**, но это не точно

Думаю что сделать отдельную Playground папку и туда кидать тестовые хосты вместе с Playground проектом будет вполне валидно.

2022-07-23 13:44 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        return new GitHubClient(new ProductHeaderValue($"Installation-{installationId}"))
Дак его там и не было, я тут только докинул кеширование :)

2022-07-27 21:48 UTC, lipa44 commented
## Подведу итог данного ПР:

1. Реализовано реагирование на вебхуки и _пока что_ комментарий в ответ на каждый ивент
2. Реализована авторизация для гита и кеширование клиентов, необходимых для действий от лица организации

## TODO/Research:

- [ ] Я бы хотел посмотреть в сторону кеша на `ignite`/`redis` - как минимум поресёрчить на эту тему
- [ ] Нужно встроить кастомный `CredStore` в существующую фабрику клиентов
- [ ] Нужно дождаться доменного АПИ и реализовать адекватный хендлинг ивентов

Если текущий функционал всех устраивает, можно заливать ПР и потом уже его допиливать

2022-07-28 04:25 UTC, FrediKats approved these changes

2022-07-28 19:52 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        return new GitHubClient(new ProductHeaderValue($"Installation-{installationId}"))
@darksidersstrife запилишь в этом ПР или замержим и потом сделаешь?

2022-07-28 19:54 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Extensions/ServiceCollectionExtensions.cs
> +
Ладно, пофиксил)

2022-07-28 19:55 UTC, lipa44 commented
@darksidersstrife я все свои конверсейшены резолвнул, жду тогда тебя и можем мержить

2022-07-30 15:44 UTC, darksidersstrife commented on Source/Integrations/Kysect.Shreks.GithubIntegration/Client/InstallationClientFactory.cs
> +        return new GitHubClient(new ProductHeaderValue($"Installation-{installationId}"))
Там одна строчка, но прямо сейчас нет возможности проверить работу, так что давай в отдельном

2022-07-30 15:45 UTC, merged