Feat: Google sheets
kysect/Shreks pull request #29
Opened 2022-07-27 22:02 UTC by Mihinator3000

2022-07-27 22:18 UTC, lipa44 reviewed
Мб как-то можно избавиться от `List<object>` и создать структуры под эти объекты, чтобы было более читаемо и реюзабельно?

2022-07-27 22:18 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public int Id { get; init; }
он где-то инициализируется?

2022-07-27 22:18 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/SubmissionExtensions.cs
> +            "https://github.com/kysect/Shreks/pull/29"
мб прокидывать ссыль через параметры? 
мы же явно с разными ПР'ами будем работать

2022-07-27 22:18 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    public async Task<T> GetOrCreateSheetAsync<T>(CancellationToken token)
```suggestion
    public async Task<T> GetOrCreateSheetAsync<T>(CancellationToken token = default)
```

ты же до этого писал дефолт - где-то он есть, а где-то нет..

2022-07-27 22:18 UTC, lipa44 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/RandomUtilities.cs
> +    public static int GetRandomId() => Random.Next();
мб что-то не понимаю, но чем гуид не угодил?)

2022-07-27 22:20 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/SubmissionExtensions.cs
> +            "https://github.com/kysect/Shreks/pull/29"
Жду #26

2022-07-27 22:22 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    public async Task<T> GetOrCreateSheetAsync<T>(CancellationToken token)
Ну default есть только в методах, которые нужны для работы с GoogleTableAccessor, из них он прокидывается во все остальные

2022-07-27 22:23 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/RandomUtilities.cs
> +    public static int GetRandomId() => Random.Next();
Не уверен что id таблицы может быть гуидом, я только инты видел

2022-07-27 22:24 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public int Id { get; init; }
Ага, при создании

2022-07-27 22:29 UTC, Mihinator3000 commented
Если честно не думал, что IList<object> могут еще где-то использоваться, структуры под них это и есть сами Core энтити, но мб я не прав, интересно еще мнений послушать

2022-07-28 04:41 UTC, FrediKats reviewed
Я не очень эксперт в гугл апи, особо не могу подсказать. У меня вопрос только по тому, какие у нас в итоге зависимости будут. Надо бы потом диаграмму нашей архитектуры сделать.

2022-07-28 04:41 UTC, FrediKats commented on Source/Domain/Kysect.Shreks.Abstractions/Kysect.Shreks.Abstractions.csproj
> +
Мне кажется, что тут что-то пошло не по плану, если у нас Abstractions зависит от Core. Подозреваю, что это из-за сущностей, которые мы в сигнатуре используем. Нужно понять судьбу этого проекта и подумать как у нас архитектура модулей.

2022-07-28 04:41 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Attributes/GoogleSheet.cs
> +public class GoogleSheetAttribute : Attribute
А почему название класса без Attribute?

2022-07-28 04:41 UTC, FrediKats commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +}
Возможно, это понадобиться не только в Google.

2022-07-28 08:16 UTC, Mihinator3000 commented on Source/Domain/Kysect.Shreks.Abstractions/Kysect.Shreks.Abstractions.csproj
> +
Ну этого проекта уже получается не существует, я просто перекину интерфейс в Integraions.Google проект

2022-07-28 08:17 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Attributes/GoogleSheet.cs
> +public class GoogleSheetAttribute : Attribute
Я где-то видел, что так делают, чтобы не писать каждому классу в папке атрибуты, Attribute в конце, но если так не понятно, могу переделать

2022-07-28 08:19 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +}
Немного не понял о чем комментарий, это типа в другом проекте должно быть или что не так?

2022-07-28 14:25 UTC, hrrrrustic commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +}
Да, унести куда-то в кор, чтобы использовать откуда угодно

2022-07-28 14:25 UTC, hrrrrustic commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentPointsExtensions.cs
> +    public static string GetStudentIdentifier(this StudentPoints studentPoints)
Вот это возможно тоже надо унести в какой-то кор

2022-07-28 16:24 UTC, Mihinator3000 commented on Source/Domain/Kysect.Shreks.Abstractions/IGoogleTableAccessor.cs
> +    Task UpdateQueueAsync(IEnumerable<Submission> submissions, CancellationToken token = default);
Это про то, что нужно обертку создать для аргументов?

2022-07-28 16:27 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Exceptions/GoogleTableException.cs
> +public class GoogleTableException : Exception
Он писал, что нужно использовать ShreksApplicationException, но гугл таблицы же не должны от Applciation зависеть

2022-07-28 16:30 UTC, hrrrrustic commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Exceptions/GoogleTableException.cs
> +public class GoogleTableException : Exception
Ну это да, думал может у вас для всех интеграцией имеется какой-то базовый

2022-07-28 16:32 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +            .ExecuteAsync(token);
А это просто коммент или надо переделать? Тут просто сильно нестинг убрать не получится

2022-07-28 16:32 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +}
Самому студенту добавить?

2022-07-28 16:34 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Exceptions/GoogleTableException.cs
> +public class GoogleTableException : Exception
Я такого не нашел, если честно + этот эксепшен только в 1 месте кидается и мне кажется его нужно тут же обработать будет и он не должен куда-то прокидываться

2022-07-28 16:59 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +}
На этот счёт уже поднимался вопрос. Для этой задачи стоит сделать отдельную абстракцию, что-то типа `IUserFullNameFormatter`, имя можно получше придумать))

2022-07-28 17:00 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Exceptions/GoogleTableException.cs
> +public class GoogleTableException : Exception
Насчёт эксепшенов и структуры проекта, сейчас это всё в очень нестабильном стейте. Думаю что такие вопросы лучше решать таской на рефактор после того как всё смержится.

2022-07-28 17:07 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentPointsExtensions.cs
> +    public static string GetStudentIdentifier(this StudentPoints studentPoints)
> Вот это возможно тоже надо унести в какой-то кор

Вообще не выглядит как какая-то кор логика. 100% консерн презентейшена в виде гугл таблиц.

2022-07-28 17:08 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +            .ExecuteAsync(token);
Ну, с созданием самого реквеста особо ничего не сделаешь, но можно как минимум не создавать объект прямо в вызове метода, а сделать его отдельной переменной.

2022-07-28 17:21 UTC, ronimizy commented
Пока что мне это кажется чем-то очень хаотичным. Надо потратить чуть больше времени на то, чтобы подробнее понять реализацию и какие-то саджесчены по улучшению дать.
Что могу сказать уже сейчас, так это то, что кодстайл у тебя оч хромает, читать болезненно. 
1. Не надо быть помешанным на инлайнах. Пусть твой код будет не в одну строчку, а в 5, но за то будет понятно что происходит. Не бойся разбивать вычисления и создания объектов на несколько шагов. Лучше твой код будет более объёмным и последовательным, чем компактной кашей.
Тут я говорю про какие-либо вычисления, создания объектов напрямую в вызовах методов 
```cs
await _service.Spreadsheets.BatchUpdate(new BatchUpdateSpreadsheetRequest 
{
    Requests = new List<Request>
    {
        new()
        {
            AddSheet = new AddSheetRequest
            {
                Properties = new SheetProperties
                {
                    Title = title,
                    SheetId = sheetId
                }
            }
        }
    }
}, _spreadsheetId)
.ExecuteAsync(token);
```
^ Это в идеале должно вызывать у тебя рвотный рефлекс)

2. Используй [expression bodied members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members) правильно.
Тело должно быть синглайн, в методах аргумент лист тоже должен быть сингллайн. Если эти условия не выполнены, или если речь идёт о конструкторе – ставь скобки.
```cs
public async Task SetAlignmentAsync(
    SheetRange sheetRange,
    HorizontalAlignment alignment,
    CancellationToken token)
    => await ExecuteBatchUpdateAsync(new Request 
    {
        RepeatCell = new RepeatCellRequest
        {
            Cell = new CellData
            {
                UserEnteredFormat = new CellFormat
                {
                    HorizontalAlignment = alignment,
                    VerticalAlignment = VerticalAlignment.Middle
                }
            },
            Range = sheetRange.GridRange,
            Fields = UpdatedFields.All
        }
    }, token);
```
^ Это в идеале должно вызывать у тебя двойной рвотный рефлекс)

2022-07-28 17:51 UTC, Mihinator3000 commented
@ronimizy, а откуда правила по [expression bodied members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)? Просто очень часто встречал, даже в публичных библиотеках `=>` и мультилайн

2022-07-28 18:05 UTC, ronimizy requested changes
В общем и целом реализация (в плане рендера таблиц, по реализации вокруг неё есть вопросы) пока норм.
Я сейчас в свободное время крафчу кое-что более абстрактное и универсальное для билдинга лейаута таблиц, но пока хз как скоро это увидит свет, так что пока пусть будет. 
Мб если понравится с гугл таблицами работать и желание будет, можешь помочь с интеграцией гугл таблиц в либу)

Короче, шлифуй архитектуру и кодстайл, я тебя просто так не отпущу)

2022-07-28 18:08 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +        }, token);
Я просто подумал, что я ж не библиотеку пишу для использования, а у себя в любом случае только Middle хотелось бы видеть

2022-07-28 18:11 UTC, ronimizy commented
> @ronimizy, а откуда правила по [expression bodied members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)? Просто очень часто встречал, даже в публичных библиотеках `=>` и мультилайн

Здравый смысл и чувство прекрасного) 
Те, кто в этих публичных библиотеках так сделали – плохие люди. Не всегда, то что можно скачать с нюгета – верное решение.

2022-07-28 18:11 UTC, ronimizy commented
> Здравый смысл и чувство прекрасного) 

Кодстайл в принципе как раз про это))0

2022-07-28 18:15 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Users/Student.cs
> +    public Student(string firstName, string? middleName, string lastName, StudentGroup group)
*
В текущей реализации это так. Возможно это не самое лучшее решение, и `null` является более корректным вариантом представления отсутствия отчества. 
НО!
Это изменение доменной сущности, такие вещи должны обговариваться с командой и изменяться при консенсусе, точно не самовольно. 
Этикет командной разработки так сказать)

2022-07-28 18:18 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +        }, token);
Факт, писать библиотеку обёртку над гугл апи это абсолютно идиотская идея. Но каких-то констант в коде хотелось бы видеть минимально. Лучше параметризовать и сделать экстеншн-перегрузку где ты передаёшь `.Middle`

2022-07-28 18:43 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +        int sheetId = await GetSheetIdAsync(title, token) ?? await CreateSheetAsync(title, token);
Придется из-за этого везде еще .Value вызывать, т.к. у нас sheetId будет `int?`. Это точно надо менять?

2022-07-28 18:47 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +        int sheetId = await GetSheetIdAsync(title, token) ?? await CreateSheetAsync(title, token);
`.Value` лучше чем `await ... ?? await ...` кмк. Если вопрос спорным кажется, можешь тегнуть Фреди в дискорде и спросить.

2022-07-28 18:48 UTC, Mihinator3000 commented on Source/Domain/Kysect.Shreks.Abstractions/IGoogleTableAccessor.cs
> +    Task UpdateQueueAsync(IEnumerable<Submission> submissions, CancellationToken token = default);
@hrrrrustic

2022-07-28 18:53 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Abstractions/IGoogleTableAccessor.cs
> +    Task UpdateQueueAsync(IEnumerable<Submission> submissions, CancellationToken token = default);
Я думаю что он скорее про то, что лучше юзать `IReadOnlyCollection<T>`.

2022-07-28 18:58 UTC, Mihinator3000 commented on Source/Domain/Kysect.Shreks.Core/Users/Student.cs
> +    public Student(string firstName, string? middleName, string lastName, StudentGroup group)
Ок, понял)

2022-07-28 19:00 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +        new("^[a-zA-Z0-9]*$", RegexOptions.Compiled);
Выглядит довольно длинно, даже в Suggested Change гх сам переносит..

2022-07-28 19:13 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +        new("^[a-zA-Z0-9]*$", RegexOptions.Compiled);
Ну, на то как в саджесченах гх форматирует особо ориентироваться не надо. У тебя в райдере есть полоска обозначающая максимальную длину + автоформатирование. В этом случае всё норм.
![Screenshot 2022-07-28 at 22 13 14](https://user-images.githubusercontent.com/71693183/181619048-37935b35-01c8-42fa-9619-273cfa312f47.png)

2022-07-28 19:17 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +        new("^[a-zA-Z0-9]*$", RegexOptions.Compiled);
Есть только одна проблема, нету райдера.. Но ладно, пофикшу

2022-07-28 19:19 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +        new("^[a-zA-Z0-9]*$", RegexOptions.Compiled);
Ну в вижле такое тоже наверняка есть. А так… лучше райдер поставь, пока учебная лицензия есть)

2022-07-28 19:29 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +        => new UserFullNameFormatter(student).GetFullName();
Не уверен, что это получится сделать, учитывая, что я вызываю метод внутри `PointsSheet`, а он не очень то хочет в DI контейнер закидываться

2022-07-28 19:33 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/StudentExtensions.cs
> +        => new UserFullNameFormatter(student).GetFullName();
Опять же, когда сделаешь фабрику щитов, то можешь форматер в реализацию фабрики принимать и прикидывать в щит при создании. Не проблема)

2022-07-28 19:36 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    }
Типа добавить в каждый sheet статическое поле с SheetCreateArguments или я что-то не улавливаю?

2022-07-28 19:40 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    }
Я бы с радостью сделал через static abstact, но до ноября не могу

2022-07-28 19:47 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    }
Не улавливаешь)
Давай на сиквенсе создания щита рассмотрим. 

1. В метод создания щита прилетает `SheetDescriptor` и `ISheetFactory<T>`. 
В дескрипторе будут такие же данные как сейчас в атрибуте. Чисто теоретически инстанс **ДЕСКРИПТОРА** можно хранить статическим свойством в типа щита. 
2. Ты получаешь айди щита / создаёшь новый
3. Ты создаёшь инстанс `CreateSheetArgs`.
В них хранится общая инфа для создания таблиц: ренжи, название, айдишник, эдитор. 
4. Ты кидаешь инстанс `CreateSheetArgs` в фабрику. 
Внутри фабрики (конкретная реализация под конкретный тип щита) новый инстанс щита создаётся через конструктор, фабрика прикидывает туда нужные аргументы из `CreateSheetArgs` плюс необходимые зависимости, которые были получены фабрикой через конструктор из di. 
5. Возвращаешь объект щита тому кто вызывал метод.

2022-07-28 19:49 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +    }
У `ISheetFactory<T>` соотвественно есть метод `T Create(CreateSheetArgs)`

2022-07-30 20:41 UTC, ronimizy requested changes
Уже лучше, но есть места где кодстайл не поправил. 
Плюс много где довольно не оптимальна реализована логика работы с коллекциями, хотелось бы видеть использование LINQ и ленивых вычислений. Эти умения оч полезны для дальнейшей разработки, так что советую потратить на это время и разобраться.

2022-07-30 20:41 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Formatters/UserFullNameFormatter.cs
> +        if (user.MiddleName != "")
```suggestion
        if (!string.IsNullOrEmpty(user.MiddleName))
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +    }
Метод написан не оптимально и читается плохо.

Почитай про [`Enumerable.Repeat`](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.repeat) ,для того чтобы создать `IEnumerable` из одного значения, про [`Enumerable.Append`](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.append), для того чтобы добавить одно значение к существующему `IEnumerable`, [`Enumerable.Concat`](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.concat) для того чтобы добавить `IEnumerable` значений к существующему `IEnumerable`.

Для замены того что ты делаешь с `.ForEach`. Можешь вынести это в отдельный метод, возвращающий `IEnumerable<object>`, почитай про кейворд `yield`, сделай это с помощью него.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +        => points == 0 ? "" : PointsToString(points);
```suggestion
        => points == 0 ? string.Empty : PointsToString(points);
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +        => dateOnly?.ToString("dd.MM.yyyy") ?? "";
```suggestion
        => dateOnly?.ToString("dd.MM.yyyy") ?? string.Empty;
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/GoogleTableAccessor.cs
> +            });
```suggestion
        var service = new SheetsService(new BaseClientService.Initializer
        {
            HttpClientInitializer = credential
        });
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/GoogleTableAccessor.cs
> +    }
Корень di – точка запуска приложения. Если ты хочешь сделать конфигурацию проще, то можешь сделать экстеншен метод на `IServiceCollection`, где будут добавляться эти сервисы.
Вообще стоит немного пересмотреть конфигурацию, потому как вот такой бутстрап твоего сервиса будет оч тяжело заимплементить и не особо удобно использовать, думаю это тема для завтрашнего мита.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/ColumnWidth.cs
> +    private readonly int _width;
Нет смысла делать это классом и плодить лишние аллокации. Сделай `record struct`

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/ColumnWidth.cs
> +    }
Этот кусок логики абсолютно не принадлежит этому типу.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Factories/IRangeFactory.cs
> +}
Аааа, не думаю что это что-то для чего стоит делать абстракцию. Лучше будет сделать два статик класса `DimensionRangeFactory` и `GridRangeFactory` с методом `.Create` у каждой.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +public class SheetRange
Этому совсем не обязательно быть классом.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public GoogleTableEditor Editor { get; init; } = null!;
Сделай нормальный конструктор.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +                                              ?? Enumerable.Empty<Assignment>();
Тут всё ещё как-то грустно.

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        });
```suggestion
        IList<IList<object>> values = await Editor.GetValuesAsync(DataRange, token);

        IList<object>? studentRow = values.FirstOrDefault(row =>
        {
            string rowIdentifier = $"{row[0]}{row[1]}";
            return rowIdentifier == studentIdentifier;
        });
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
```suggestion
        if (studentRow is null)
        {
            var message = $"Student with identifier {studentIdentifier} was not found";
            throw new GoogleTableException(message);
        }
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        await Editor.ResizeColumnsAsync(ColumnLengths, Id, token);
```suggestion
        var properties = new SheetProperties
        {
            SheetId = Id,
            GridProperties = new GridProperties
            {
                FrozenColumnCount = FrozenColumnCount
            }
        };

        await Editor.ClearValuesAsync(HeaderRange, token);
        await Editor.SetAlignmentAsync(HeaderRange, token);
        await Editor.FreezeRowsAsync(HeaderRange, token);
        await Editor.FreezeColumnsAsync(properties, token);
        await Editor.MergeCellsAsync(GetMergeRanges(assignments.Count), token);
        await Editor.SetValuesAsync(GetHeader(assignments), HeaderRange, token);
        await Editor.ResizeColumnsAsync(ColumnLengths, Id, token);
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/QueueSheet.cs
> +        };
```suggestion
    private static readonly IList<object> Header = new List<object>
    {
        "ФИО",
        "Группа",
        "Лабораторная работа",
        "GitHub"
    };
```

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleSheetCreator.cs
> +
Вынеси создание объекта реквеста

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +    }
Вынеси лямбду из селекта в отдельный метод

2022-07-30 20:41 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
```suggestion
        await _service.Spreadsheets.Values.BatchUpdate(batchUpdateRequest, _spreadsheetId).ExecuteAsync(token);
```

2022-07-30 20:47 UTC, Mihinator3000 commented on Source/Domain/Kysect.Shreks.Core/Formatters/UserFullNameFormatter.cs
> +        if (user.MiddleName != "")
Мне кажется это немного сбивающе, зачем нам на null проверять лишний раз?

2022-07-30 20:48 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +        => points == 0 ? "" : PointsToString(points);
А с этим то что не так?

2022-07-30 20:49 UTC, ronimizy commented on Source/Domain/Kysect.Shreks.Core/Formatters/UserFullNameFormatter.cs
> +        if (user.MiddleName != "")
Это стандартный способ проверять на пустую строку.

2022-07-30 20:50 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +        => points == 0 ? "" : PointsToString(points);
На самом деле с технической точки зрения разницы 0, но такой вариант предпочтителен, так как читается лучше чем пустой литерал.

2022-07-30 20:52 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/GoogleTableAccessor.cs
> +            });
А это точно лучше читается так?

2022-07-30 20:56 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/GoogleTableAccessor.cs
> +            });
Фигурные скобки с уровнем индентации выше чем текущий в общем выглядят очень плохо. Если такой вариант не нравится, то можно вынести `Initializer` в отдельную переменную.

2022-07-30 21:02 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public GoogleTableEditor Editor { get; init; } = null!;
То есть конструктор с 7 параметрами? Это же вообще криво будет выглядеть..
![image](https://user-images.githubusercontent.com/70411602/181996050-f97dbb58-5807-402d-8cd2-71fcf7784420.png)

2022-07-30 21:15 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
А в чем прикол переносить в середине вызова одной функции вместо того, чтобы это делать между вызовами?

2022-07-30 21:17 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
А прикол в том что переноса нет) это всё форматирование гх

2022-07-30 21:21 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public async Task UpdateStudentPointsAsync(StudentPoints studentPoints, CancellationToken token)
Я думал, что метод UpdatePoints будет как раз для обновления всей таблицы (при изменении информации о ассайнментах или студентах), а UpdateStudentPoints будет для обновления баллов 1 студента.
Если все же оставим два метода, то я починю чтобы обновлялись не все ячейки, и тогда наверное конфликтов не должно быть

2022-07-30 21:24 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public GoogleTableEditor Editor { get; init; } = null!;
@ronimizy

2022-07-30 21:25 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
Опять если честно какой-то странный suggestion, вроде читается одинаково нормально в обоих вариантах

2022-07-30 21:28 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public GoogleTableEditor Editor { get; init; } = null!;
Ну, 7 параметров эт в общем не норм. Но тут скорее вопрос архитектуры. Синтаксически норм. Если тебе параметров много кажется, принимай в конструктор `SheetCreateArgs`.

2022-07-30 21:31 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
Вообще на самом деле норм даже без переноса. Просто переносы, особенно такие единичные, выглядят не лаконично, поэтому лучше закидывать в локальную переменную. Смотря на то, какие у тебя в коде стоят переносы, складывается ощущение, что у тебя в IDE максимальная длина строки слишком низкая стоит.

2022-07-30 21:34 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
Попробуй поставить hard wrap на 120.

2022-07-30 21:35 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
Самое забавное, это то, что когда я кидал саджесчен, то в превью тут был горизонтальный слайдер)

2022-07-30 21:36 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +public class SheetRange
Если честно, не очень понимаю что не так с классами, что в данном случае лучше использовать, record struct?

2022-07-30 21:42 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
Вообще я сам переношу, мне кажется так читается легче..

2022-07-30 21:44 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
А, ок, так еще более-менее. Я просто привык не писать два вызова на одной строчке, поэтому переношу. Мне кажется это логичнее слегка

2022-07-30 21:47 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Factories/IRangeFactory.cs
> +}
Ну насчет абстракции я согласен, что лишнее, но мне кажется лучше сделать одну фабрику все-таки, раз нам нужно передавать sheetId в создании рэнжей

2022-07-30 21:56 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +public class SheetRange
Суть классов в том, что они ссылочные типы, а значит под них выделяется память на куче, что будет приближать систему к моменту когда начнётся сборка мусора. Есть места где ссылочные типы имеют смысл, шаренный стейт, в общем всё остальное вытекает либо из этого или из возможности наследования. Когда тебе надо просто собрать какие-то данные в одном месте, чтобы в дальнейшем их обработать, смысла делать такую модель ссылочным типом нет. Так как она ридонли, значения внутри неё не поменяются, если она хранит референс, то он будет указывать на тот же самый объект во всех копиях. В общем, с точки зрения дальнейшего использования, разницы в том, прилетел тебе в метод тот самый инстанс который ты создал, или копия – нет, а вот по производительности и памяти ты выигрываешь.

Что касается record/не record. Тут всё сводится к тому, есть ли у тебя какая-то логика обработки данных перед инициализацией объекта. В данном случае ты делаешь валидацию, поэтому тебе придётся писать свой конструктор, свои поля. Так что, если только тебе где-то не нужно иметь возможность сравнить два инстанса почленно, вся компиляторная магия рекордов становится бесполезной и скорее будет вести к ухудшению понимая кода.

Ну в общем, вам [сюда](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records)

2022-07-30 22:00 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +        }
Ну, 120 символов вполне разумная максимальная длина. Вжатый влево код растёт ввысь, что тоже не есть хорошо, не считая того, что вжатый код сам по себе ниоч)

2022-07-30 22:09 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Models/SheetRange.cs
> +public class SheetRange
0_0

2022-07-30 22:14 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Factories/IRangeFactory.cs
> +}
Передавай аргументом, в чём проблема. Зачем лишний раз объект создавать ради переиспользования инта...

2022-07-30 22:17 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Tools/GoogleTableEditor.cs
> +            .ExecuteAsync(token);
Ну `ExecuteAsync` оч короткий, как то там болтается не понятно как. Либо оба переноси с новой строчки, либо оба на одной.

2022-07-30 23:19 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Converters/StudentPointsConverter.cs
> +    }
Честно не особо понял к чему тут [Enumerable.Repeat](https://docs.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.repeat), но все остальное вроде сделал

2022-07-31 09:05 UTC, ronimizy requested changes

2022-07-31 09:05 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    }
Мне кажется что это не так работает)
Ты теряешь задания по которым у студента нет баллов.

2022-07-31 09:05 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +            .ToList();
Думаю что тебе нет смысла упорядочивать поинты для того чтобы получить список всех заданий. Ты можешь просто через `SelectMany` и `DistinctBy` получить все уникальные задания (так же относится к комменту ниже). Что позволит тебе получить значения без материализации промежуточной коллекции.

Вообще такая логика форматирования кажется не особо верной. Что будет если есть лабы по которым у студентов нет баллов? Они не отрисуются в таблице.

2022-07-31 09:39 UTC, Mihinator3000 commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +            .ToList();
Тогда наверное лучше будет создать еще 1 рекорд, который будет хранить в себе сначала все задания, а потом оценки всех студентов по этим заданиям

2022-07-31 15:33 UTC, FrediKats approved these changes
На коле обсудили, что в целом всё ок.

2022-07-31 19:10 UTC, ronimizy approved these changes

2022-07-31 19:10 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    }
```suggestion
    public async Task UpdatePointsAsync(Points points, CancellationToken token)
    {
        await Editor.ClearValuesAsync(DataRange, token);

        List<Assignment> orderedAssignments = points.Assignments
            .OrderBy(a => a.Title)
            .ToList();

        await FormatAsync(orderedAssignments, token);

        IList<IList<object>> values = points.StudentsPoints
            .OrderBy(p => p.Student.Group.Name)
            .ThenBy(p => _userFullNameFormatter.GetFullName(p.Student))
            .Select(s =>
            {
                var studentPointsArguments = new StudentPointsArguments(orderedAssignments, s);
                return _studentPointsConverter.GetSheetRow(studentPointsArguments);
            })
            .ToList();

        await Editor.SetValuesAsync(values, DataRange, token);
    }
```

2022-07-31 19:11 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Sheets/PointsSheet.cs
> +    public async Task UpdateStudentPointsAsync(StudentPoints studentPoints, CancellationToken token)
Обговорили решение данной проблемы на мите

2022-07-31 19:11 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/GoogleTableAccessor.cs
> +    }
Обговорили решение данной проблемы на мите

2022-07-31 19:12 UTC, ronimizy commented on Source/Integrations/Kysect.Shreks.GoogleIntegration/Extensions/Entities/SubmissionExtensions.cs
> +            "https://github.com/kysect/Shreks/pull/29"
Будет решено на моменте интеграции в систему (обговорили решение данной проблемы на мите).

2022-08-01 06:57 UTC, FrediKats requested changes

2022-08-01 06:57 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
> +	<Content Include="client_secrets.json">
Билд падает с тем, что в csproj прописано копирование файла, а файл не добавлен. Можем добавить пустой json, чтобы билд не фейлился?

2022-08-01 07:11 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
> +	<Content Include="client_secrets.json">
Думаю лучше будет даже вообще удалить, всё равно на этапе интеграции в систему надо будет это менять.

2022-08-01 07:21 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Kysect.Shreks.Integration.Google.csproj
> +	<Content Include="client_secrets.json">
Обсудили в дискорде, что для простоты тестирования оставим пустой.

2022-08-01 07:27 UTC, FrediKats commented
Даю отчёт, что оно не билдится.

2022-08-01 07:27 UTC, merged