docs: add docs from notion
kysect/Shreks pull request #41
Opened 2022-07-31 12:22 UTC by FrediKats

close #15 
close #16
close #36

2022-07-31 15:44 UTC, luck-o-o-luck reviewed
Часто встречаемые слова - контекст и решение. Мб стоит выделить их жирным шрифтом или же писать примерно так: "Контекст: раньше все..."?

2022-07-31 16:02 UTC, luck-o-o-luck requested changes

2022-07-31 16:02 UTC, luck-o-o-luck commented on Docs/TechDocs/UseRichEntity.md
> +Для `partial` типов, реализующих интерфейс `IEntity` по всем свойствам помеченым атрибутом
чет не так, не понимаю, как бы отрефакторить

2022-07-31 16:02 UTC, luck-o-o-luck commented on Docs/TechDocs/UseRichEntity.md
> +с именем, соответсвующим имени свойства к которому добавлено `Id` (ex: `User User` -> `Guid UserId`).
```suggestion
с именем, соответствующим имени свойства, к которому добавлено `Id` (ex: `User User` -> `Guid UserId`).
```

2022-07-31 16:02 UTC, luck-o-o-luck commented on README.md
> +Система предназначена для автоматизации процесса обучения - а именно процессов отправки заданий студентами, формирования очереди и оценивания заданий преподавателями.
```suggestion
Система предназначена для автоматизации процесса обучения, а именно: процессов отправки заданий студентами, формирования очереди и оценивания заданий преподавателями.
```

2022-07-31 16:08 UTC, Bibletoon commented on Docs/Glossary.md
> +Обучающийся, выполняющий задания, имеет ФИО, группу, номер в ИСУ, доп информация (например аккаунт на github, нужный для [курса] по программированию)
```suggestion
Обучающийся, выполняющий задания, имеет ФИО, группу, номер в ИСУ, доп информацию (например аккаунт на github, нужный для [курса] по программированию)
```

2022-08-01 07:02 UTC, FrediKats commented on Docs/Glossary.md
> +Сабмишен - отправка [студентом] результатов выполнения [задания].
Проблема в том, что ссылке непонятно на что делать. Ссылки можно на хедеры делать, а это просто текст (

2022-08-01 07:10 UTC, merged