docs: add docs about system, dev and user guides
kysect/Shreks pull request #436
Opened 2022-09-17 17:26 UTC by FrediKats

Попытался немного дополнить документацию - описать процессы, логику работы и остальное.

2022-09-18 10:41 UTC, darksidersstrife commented on Docs/Deployment-guides/Required-info-for-deploy.md
> +4. Перейти в директорию с репозиториев, выполнить git pull
Репозиторием*

2022-09-18 10:41 UTC, darksidersstrife commented on Docs/Deployment-guides/Required-info-for-deploy.md
> +- Id Google drive директории, куда пишутся данные и доступ к ней
Это ж вообще не sensitive info :thinking:

2022-09-19 20:09 UTC, annchous requested changes

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/GitHub-common.md
> +Сервис github предоставляет функционал общих аккаунтов, которые называются организациями. Github Организация - созданная на сервисе Github группа, которая предоставляет возможность добавлять в неё уч
```suggestion
GitHub имеет встроенные инструменты для поддержки Continues integration. Continues integration - практика разработки ПО, которая заключается в постоянном добавлении изменений в общий репозиторий и автоматической сборки проекта, запуска тестов для выявления дефектов или проблем.

Сервис GitHub предоставляет функционал общих аккаунтов, которые называются организациями. GitHub Организация - созданная на сервисе GitHub группа, которая предоставляет возможность добавлять в неё участников и репозитории, управлять доступами учестников к репозиториям организации.
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/Github-template-repository.md
> +Для большинства дисциплин, которые предполагают написание кода, можно и имеет смысл заранее создавать шаблон проекта. Такой шаблон будет предоставляться студентам, чтобы они его дописывали в рамках в
```suggestion
Для большинства дисциплин, которые предполагают написание кода, можно и имеет смысл заранее создавать шаблон проекта. Такой шаблон будет предоставляться студентам, чтобы они его дописывали в рамках выполнения работ. GitHub поддерживает возможность создания шаблонного репозитория. Для этого достаточно создать обычный git-репозиторий, загрузить его на GitHub и предоставить ссылку администратору СУФ. Администратор загрузит этот шаблон в организацию, и студенты будут создавать свои репозитории из этого шаблона. Шаблон позволяет:
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/Github-template-repository.md
> +Для большинства дисциплин, которые предполагают написание кода, можно и имеет смысл заранее создавать шаблон проекта. Такой шаблон будет предоставляться студентам, чтобы они его дописывали в рамках в
СУФ

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/Github-template-repository.md
> +- Определить инструменты. Например, созданный проект будет содержать код с использованием .NET 6, а значит студенты не смогут случайно создать неправильную версию
```suggestion
- Определить инструменты. Например, созданный проект будет содержать код с использованием .NET 6, а значит студенты не смогут случайно использовать неправильную версию;
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/Github-template-repository.md
> +- Определить структуру решения. Если в шаблонном репозитории уже созданы директории под каждую работу, то уменьшается вероятность, что они задумаются о создании отдельных репозиториев на каждую работ
```suggestion
- Определить структуру решения. Если в шаблонном репозитории уже созданы директории под каждую работу, то уменьшается вероятность, что они задумаются о создании отдельных репозиториев на каждую работу;
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Knowledge-base/Github-template-repository.md
> +- Добавления проверок и тестов. Github позволяет задать для репозитория поведение при создании Pull request. Таким поведением может являться проверка кода встроенным в язык/систему сборки анализаторо
```suggestion
- Добавление проверок и тестов. GitHub позволяет задать для репозитория поведение при создании Pull request. Таким поведением может являться проверка кода встроенным в язык/систему сборки анализатором. Например, компилятор .NET'а позволяет не только проверить, что проект не содержит ошибок компиляции, но и сразу получить предупреждения о проблемах в коде - нарушения код стайла, потенциальные null reference exception и другое. Также используя CI можно настроить автоматический запуск тестов при создании Pull request. Это даст гарантию того, что студент загружает правильный код.
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Bug-reporting.md
> +- Цель: Выявление, фиксация и устранение проблем при использовании СУФ
СУФ

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Setup-subject-github-organization.md
> +5. Поддержка добавляем преподавателей и менторов в организацию и предоставляет правда на чтение приватных репозиториев
```suggestion
5. Поддержка добавляет преподавателей и менторов в организацию и предоставляет права на чтение приватных репозиториев
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Setup-subject-github-organization.md
> +6. Студенты авторизуются в системе используя свои учётные записи аффилированные с университетом и учётные записи Github, которые они будут использоваться в ходе курса. (*)
```suggestion
6. Студенты авторизуются в системе, используя свои учётные записи, аффилированные с университетом, и учётные записи GitHub, которые они будут использовать в ходе курса. (*)
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Setup-subject-github-organization.md
> +- Если в течении 7 дней студент не принимает приглашение в организацию, то оно устаревает и больше не актуальное. В таком случае нужно обратиться в поддержку и запросить повторную отправку приглашени
```suggestion
- Если в течение семи дней студент не принимает приглашение в организацию, то оно устаревает и больше не является актуальным. В таком случае нужно обратиться в поддержку и запросить повторную отправку приглашения.
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Setup-subject-github-organization.md
> +- В процессе прохождения курса очень не рекомендуется изменять github username, но если так произошло, то стоит обратиться в поддержку и предоставить ему данные об изменениях
```suggestion
- В процессе прохождения курса очень не рекомендуется изменять github username, но если так произошло, то стоит обратиться в поддержку и предоставить ей данные об изменениях.
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Upload-assignment-solution.md
> +1. Студент приступает к решению задания, знакомиться с условием и создаёт branch в своём локальном репозитории
```suggestion
1. Студент приступает к решению задания, знакомится с условием и создаёт branch в своём локальном репозитории
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Upload-assignment-solution.md
> +3. Студент выполняет push своей ветки на Github и создаёт pull request из неё в мастер
```suggestion
3. Студент выполняет push своей ветки на GitHub и создаёт pull request из неё в мастер
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Upload-assignment-solution.md
> +   2. Если к работе есть замечания, то преподаватель request changes
```suggestion
   2. Если к работе есть замечания, то преподаватель делает request changes
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Upload-assignment-solution.md
> +   2. Если к работе есть замечания, то преподаватель request changes
Либо тогда уже requests

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Upload-assignment-solution.md
> +8. По окончанию работы над pull request происходит его merge
```suggestion
8. По окончании работы над pull request происходит его merge
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Working-with-github-for-students.md
> +Сдача исходного кода выполненных работ происходит с использованием сервиса Github и функциональности организаций, которую он предоставляет.
```suggestion
Сдача исходного кода выполненных работ происходит с использованием сервиса GitHub и функциональности организаций, которую он предоставляет.
```

2022-09-19 20:09 UTC, annchous commented on Docs/User-guides/Scenarios/Working-with-github-for-students.md
> +9. Если в результате защиты был получен не максимальный балл, то работу можно доделать. Изменения должны писаться в той же ветке, где и была написана работа. Созданные новые комиты нужно запушить в т
СУФ

2022-09-19 20:09 UTC, annchous commented
По смыслу - очень много всего повторяется. Так и должно быть?

2022-09-21 13:45 UTC, FrediKats commented
Повторяется т.к. часть описано в контексте разработки, а часть - для пользователей. Но предложения принимаются.

2022-09-22 18:21 UTC, FrediKats commented on Docs/Dev-docs/LIbs/Readme.md
> +- dotnet
Ну... Не знаю, стоит ли вообще описывать.

2022-09-22 18:22 UTC, annchous approved these changes
Сейчас нет особо вдохновения предлагать переструктурированный текст, поэтому пусть будет так (даже если там есть повторения). Позже можно будет поправить.

2022-09-22 18:27 UTC, merged