Feat: seeding
kysect/Shreks pull request #44
Opened 2022-07-31 12:53 UTC by luck-o-o-luck

closes #24

Немного не дописала тесты, кажется, что есть проблемы с UserAssociation, обсужу с Гошей. Сидинг доделаю после тестов.

2022-07-31 13:21 UTC, ronimizy commented
Скажу сразу. Нет смысла в лишней вербозности нейминга папок. То есть, если у тебя есть папка "EntityGenerators", то в подпапках не нужно писать постфикс "Generators". Это как делать у типа `User` свойство `UserId`.

2022-07-31 13:42 UTC, ronimizy requested changes
Тебе нужно вмержить мастер в свою ветку.

Гитхаб CI, судя по опыту, перед тем как билдить ветку, мержит её с мастером локально. В мастере есть параметр конструктора `DateTime submissionDateTime`, а у тебя нет, соответсвенно билд фейлится на моменте когда у тебя в генераторе вызывается конструктор, который в смеренной версии имеет на один параметр больше, чем аргументы, которые передаёшь ты.

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/StudyGenerators/GroupAssignmentGenerator.cs
> +    }
Вообще тут есть вероятность того что для двух индексов будет сгенерен одинаковый GroupAssignment. Так как есть вероятность рандомом пикнуть два раза одну пару (Group, Assignment). 
Так что тут скорее надо не рандомом брать, а от индекса вычислять.
Номер группы = `index / assignmentCount`
Номер задания = `index % assignmentCount`
Если номер группы `>=` количества групп, то кидай `IndexOutOfRangeException`

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/StudyGenerators/StudentAssignmentGenerator.cs
> +    }
same ^

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/StudyGenerators/SubjectCourseGenerator.cs
> +    }
same ^

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/StudyGenerators/SubjectCourseGroupGenerator.cs
> +    }
same ^

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/SubjectCourseAssociationsGenerators/SubjectCourseAssociationGenerator.cs
> +    }
same ^

Только тут надо доставать курс по индексу, без каких-либо преобразований.

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociationsGenerators/GithubUserAssociationGenerator.cs
> +    }
same ^^

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociationsGenerators/IsuUserAssociationGenerator.cs
> +    }
same ^^

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserGenerators/StudentGenerator.cs
> +        StudentGroup? group = _studentGroupGenerator.GeneratedEntities[groupNumber];
```suggestion
        var group = _studentGroupGenerator.GeneratedEntities[groupNumber];
```

2022-07-31 13:42 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserGenerators/StudentGenerator.cs
> +        );
```suggestion
        var student = new Student
        (
            _faker.Person.FirstName,
            _faker.Person.UserName,
            _faker.Person.LastName,
            group
        );
```

2022-08-09 12:40 UTC, ronimizy approved these changes
LGTM

можно в тестах не проверять то, что структура объекта была правильно получена из базы, если сущность достали без эксепшена, то значит конфигурация норм

2022-08-09 18:19 UTC, FrediKats approved these changes
Кажется, что местами тесты превращаются в тесты  EF'а, но если вы говорили, что это ловит баги то, ок. В остальном выглядит ок.

2022-08-09 18:46 UTC, darksidersstrife approved these changes

2022-08-09 19:43 UTC, merged