feat/commands
kysect/Shreks pull request #65
Opened 2022-08-07 02:13 UTC by darksidersstrife

2022-08-07 04:08 UTC, FrediKats requested changes

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +            select type).ToArray();
У нас по кодстайлу запрещёл SQL-like синтаксис линков. Только на экстеншен методах.

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +public class CommandParser
Я бы в имя докинул инфы о том, что парсим.

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        var result = CommandLine.Parser.Default.ParseArguments(commandStr.Split(), _commandTypes);
CommandLine.Parser.Default бы в переменную.

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        return result.Value as ICommand;
Оно не смогло в дженерики? =_=

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        return result.Value as ICommand;
И лучше не as, а .To или что-то такое, чтобы бы null не вернули случайно. Если у нас ещё нет экстеншен метода .To, то можно где-то в Common прописать. Или сразу в Kysect.Common ))00

2022-08-07 04:08 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/ICommand.cs
> +    void Process(/*mediatr?*/);
Нам тут нужно прокидывать всякие репозитории и GithubAccessor'ы, но медиатор эту задачу не решает. Даже IoC нам тут не поможет, видимо.

2022-08-07 04:13 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/ICommand.cs
> +    void Process(/*mediatr?*/);
Справедливо, значит и правда нужно CommandProcessor сделать
А еще сюда юзера передавать, который вызвал

2022-08-07 04:36 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +public class CommandParser
Имеешь в виду GithubCommandParser?

2022-08-07 04:40 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        return result.Value as ICommand;
> Оно не смогло в дженерики? =_=
Смогло, там есть WithParsed и матчинг по типам, но там надо сразу действие осуществлять
А так ведь команды не обязаны быть все от одного интерфейса отнаследованы, так что там object, да
Но там ничего другого не может быть - все команды наследуются от интерфейса, парсинг произошел успешно 🤔 

> И лучше не as, а .To
А to должен бросать жксепшен?

2022-08-07 04:41 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +public class CommandParser
Например, да. Но тут важнее не откуда мы парсим, а во что мы парсим.

2022-08-07 04:46 UTC, FrediKats reviewed
Я ещё вспомнил, что хотел предложить не привязывать команды строго к гитхабу и не складывать их в проекте с гитхабом. Ты же сам говорил, что это очень тонкая прослойка. И команды - это не её зона ответственности.

2022-08-07 04:46 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        return result.Value as ICommand;
Да, должен, если не смогли скастить. Как обычный каст, просто в более приятном виде. Можешь просто каст бахнуть.

2022-08-07 04:55 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        var result = CommandLine.Parser.Default.ParseArguments(commandStr.Split(), _commandTypes);
А зачем?)

2022-08-07 04:56 UTC, darksidersstrife commented
Соглы, тоже об этом думал, но мне стало лень додумать, куда именно их положить)0

2022-08-07 04:59 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +public class CommandParser
Тогда непонимейшен, парсим-то просто в команды
Ну разве что это команды шрекса и он может быть ShreksCommandParser

2022-08-07 05:34 UTC, lipa44 reviewed
Наличие неизвестных мне конструкций в каждом ПР меня начинает пугать) Надеюсь, оно работает))

2022-08-07 05:34 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +            select type).ToArray();
Как же они не хотят делать енум)

2022-08-07 05:34 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/CommandParser.cs
> +        var result = CommandLine.Parser.Default.ParseArguments(commandStr.Split(), _commandTypes);
Что это........ ладно..

2022-08-07 05:34 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/ICommand.cs
> +    void Process(/*mediatr?*/);
Согл. Похоже на двойную диспетчериацию (или как там у визитора оно называется). Проще сделать CQRS комманду, которая будет это обрабатывать

2022-08-07 05:34 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/RateCommand.cs
> +[Verb("/rate", aliases: new []{"/assess", "/gachi-rate"})]
Каждый раз в ~~ах~~шоке от того чо ты пишешь)

2022-08-07 05:34 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +        services.AddSingleton<CommandParser>();
Сделать бы интерфейс и вынести парсер вместе с ним из гитхаб интеграции

2022-08-07 05:40 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +        services.AddSingleton<CommandParser>();
> Наличие неизвестных мне конструкций в каждом ПР меня начинает пугать)

А что именно?
Тут вроде ничего такого)
> Что это........ ладно..
Вызов либы
> Согл. Похоже на двойную диспетчериацию (или как там у визитора оно называется). Проще сделать CQRS комманду, которая будет это обрабатывать
Она самая, насчет проще не уверен, но спорить не готов

2022-08-07 05:57 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Commands/RateCommand.cs
> +[Verb("/rate", aliases: new []{"/assess", "/gachi-rate"})]
))

2022-08-07 06:23 UTC, lipa44 commented
> А что именно?
> Тут вроде ничего такого)

Атрибуты, которые ты юзаешь. Рефлекшн для определения типов. Какой-то CommandLine.Parser...))

2022-08-12 14:00 UTC, lipa44 commented
Ждём визиторы)

2022-08-12 23:02 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
> +            //TODO: add update extra balls command (or add them to previous command)
extra balls))))

2022-08-15 11:09 UTC, hrrrrustic commented
Тут на чем в итоге остановились?

2022-08-15 16:17 UTC, hrrrrustic commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/IShreksCommand.cs
> +    public Task<TResult> Process<TResult>(IShreksCommandProcessor<TResult> processor, ICommandContextCreator contextCreator)
```suggestion
    Task<TResult> Process<TResult>(IShreksCommandProcessor<TResult> processor, ICommandContextCreator contextCreator)
```

2022-08-15 17:18 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
> +        Guid submissionId = new Guid(SubmissionId);
Кажется либа умеет только в примитивы

2022-08-15 17:19 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Commands/Parser/IShreksCommandParser.cs
> +    IShreksCommand? Parse(string commandStr);
А TryParse подразумевает, что там все еще может вылететь исключение?

2022-08-15 18:22 UTC, FrediKats approved these changes

2022-08-15 18:22 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
> +[Verb("/rate", aliases: new []{"/assess", "/gachi-rate"})]
Ради всего святого, не тащите вот это всё в код.

2022-08-15 18:22 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
> +            RatingPercent / 100 * submission.Assignment.MaxPoints));
Я думаю, что правильно будте всё же прокидывать сырые аргументы, а приводить к баллам - это зона ответственности бизнес логики.

2022-08-15 18:22 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
> +        Guid submissionId = new Guid(SubmissionId);
Дак гуид это что-то около примитива.

2022-08-15 18:22 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/ContextCreators/IssueCommentContextCreator.cs
> +        //need pr -> submission query
Давай хоть TODO напишем, а то не найдём потом.

2022-08-15 18:22 UTC, FrediKats commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/ShreksWebhookEventProcessor.cs
> +                        e.Message);
Надо будет потом подумать, как это инкапсулировать нормально.

2022-08-15 18:52 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
> +            RatingPercent / 100 * submission.Assignment.MaxPoints));
Предполагалось что для процентов будет отдельная команда

2022-08-15 18:53 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Parser/IShreksCommandParser.cs
> +    IShreksCommand? Parse(string commandStr);
Если может вылететь исключение, зачем возвращать nullable?

2022-08-15 20:05 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
> +        Guid submissionId = new Guid(SubmissionId);
`Guid.Parse` как-то покрасивше выглядит

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/UpdateCommand.cs
> +                 RatingPercent.Value));
```suggestion
             var command = new UpdateSubmissionPoints.Command(submissionId, RatingPercent.Value);
             var response = await context.Mediator.Send(command);
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/IShreksCommand.cs
> +}
Оч хочется добавить что-то типа ..., для того чтобы форсить сигнатуры через компилятор, даже если мы в визиторе принимаем конкретные типы команд.

```cs
public interface IShreksCommand<TContext, TResponse> : IShreksCommand
{
    Task<TResponse> ExecuteAsync(TContext context, CancellationToken cancellationToken);
}
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Commands/RateCommand.cs
> +            RatingPercent / 100 * submission.Assignment.MaxPoints));
```suggestion
        var submissionId = context.Submission.Id;
        var maxPoints = context.Submission.Assignment.MaxPoints;
        var points = RatingPercent / 100 * maxPoints;
        var command = new UpdateSubmissionPoints.Command(submissionId, points);
        //TODO: add update extra points command or add extra points to this command
        var respone = await context.Mediator.Send(command);
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Contexts/ICommandContextCreator.cs
> +public interface ICommandContextCreator
```suggestion
public interface ICommandContextFactory
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Extensions/ServiceCollectionExtensions.cs
> +    public static IServiceCollection AddCommandParser(this IServiceCollection services)
Тут лучше сделать `AddApplicationCommands` и всю конфигурацию (возможную будущую) здесь добавлять.

2022-08-15 20:29 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Processors/IShreksCommandProcessor.cs
> +}
```suggestion
public interface IShreksCommandVisitor<TResult> where TResult : IShreksCommandResult
{
    Task<TResult> Visit(RateCommand rateCommand, ICommandContextCreator contextCreator, CancellationToken cancellationToken);
    Task<TResult> Visit(UpdateCommand updateCommand, ICommandContextCreator contextCreator, CancellationToken cancellationToken);
}
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/ContextCreators/IssueCommentContextCreator.cs
> +    }
```suggestion
    {
        var login = _event.Sender?.Login ?? throw new Exception();
        var query = new GetUserByUsername.Query(login);
        var response = await _mediator.Send(query);
        var issuer = await _databaseContext.Users.GetByIdAsync(response.UserId);

        return new BaseContext(_mediator, issuer);
    }
```

2022-08-15 20:29 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
> +        ParseWebhookEvent(webhookEvent, out Repository repository, out InstallationLite installation);
Пиздец кто это высрал...

2022-08-15 20:29 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +
Это лучше занести в один метод типа `AddGithubIntegration` когд будем собирать апи, будет проще не пропустить вызов нужного метода.

2022-08-15 20:29 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +        }
Я бы тут добавил метод с сигнатурой `Task<BaseShreksCommandResult> Process(Func<Task<BaseShreksCommandResult>> func)` в котором бы вызывал `func` в `try-catch` блоке, а аргументом передавал саму лямбду с обработкой команды. Потому что в коде уже норм так копипасты, а при эксепшене логика везде одинаковая, и одинаковая скорее всего и будет.

2022-08-15 20:29 UTC, ronimizy commented on Source/Playground/Kysect.Shreks.Playground.Github/Program.cs
> +    ;
```suggestion
    .AddCommandParser()
    .AddMediatR(c => c.AsSingleton(), Assembly.GetExecutingAssembly())
    .AddCommandProcessor()
    .AddWebhookProcessors();
```

2022-08-15 20:32 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Processors/IShreksCommandProcessor.cs
> +}
Ну и передачу фабрики через диспач соответсвенно нужно убрать

2022-08-15 20:35 UTC, ronimizy commented
Там ещё на парсерах бы неймспейсы поправить)

2022-08-15 20:35 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
>      }
кажется что `ApplyInComments` тогда можно удалить

2022-08-15 20:38 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
всегда `true`?)

2022-08-15 20:40 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Поч? При выполнении команды же может эксепшен вылететь

2022-08-15 20:40 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
> +        ParseWebhookEvent(webhookEvent, out Repository repository, out InstallationLite installation);
(я про метод с `out` параметрами)

2022-08-15 20:41 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
> Поч? При выполнении команды же может эксепшен вылететь

```csharp
new BaseShreksCommandResult(true, ...
```

2022-08-15 20:43 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Ну ниже же catch с false, или я чего-то не понимаю

2022-08-15 20:44 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
а я пон. да.

но выглядит оч странно

2022-08-15 21:17 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
понимаю, что могу начать новый халивар, но...

я бы сделал так:

```csharp
public class SuccessfulShreksCommandResul : IShreksCommandResult
{
    public SuccessfulShreksCommandResul(string message) => Message = message;

    public bool IsSuccess => true;
    public string Message { get; }
}
```

```csharp
public class FailedShreksCommandResult : IShreksCommandResult
{
    public FailedShreksCommandResult(string message) => Message = message;

    public bool IsSuccess => false;
    public string Message { get; }
}
```

```csharp
public class GithubCommandProcessor : IShreksCommandProcessor<IShreksCommandResult> ...
```

потому что BaseResult выглядит очень странно и прокидывание руками true/false тоже. Так имхо хотя бы есть чёткое разделение успешных и неуспешных результатов, а не проставление флагу руками.

так что это предложения вида да-да/нет-нет, спорить и задерживать ПР я не особо хочу

2022-08-15 21:35 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Поддержу, об этом сегодня в дискорде говорили, в принципе может пойти дальше и флаг убрать, определять успех через интерфейс. Но опять же, рефакторинг к сожалению запрещён 🤷🏼‍♂️

2022-08-15 21:39 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Про определение по классу тож хотел сказать, но рефакторинг запрещён, да..

2022-08-15 22:36 UTC, hrrrrustic commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Не запрещен, а отложен на потом. Ну каммон, это совсем мелочи уже

2022-08-15 22:58 UTC, hrrrrustic commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Можно сделать просто два статик метода на Success и Failed

2022-08-15 22:59 UTC, hrrrrustic commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Вот уж этого точно хватит пока

2022-08-16 17:03 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Commands/Parser/IShreksCommandParser.cs
> +    IShreksCommand? Parse(string commandStr);
Команды в комментарии может и не быть 🤷 
Впрочем, наверное можно эту проверку вынести выше

2022-08-16 17:08 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
> +        ParseWebhookEvent(webhookEvent, out Repository repository, out InstallationLite installation);
Липа, я просто скопировал)0

2022-08-16 17:09 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +        }
Так тут, если что, будет разная обработка эксепшенов для разных команд

2022-08-16 17:11 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Так а то есть в будущем на каждый новый тип резалта надо будет писать два класса, да?)

2022-08-16 17:14 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Commands/Processors/IShreksCommandProcessor.cs
> +}
> Ну и передачу фабрики через диспач соответсвенно нужно убрать
Как, простите
Ну кроме как перенести ее в визитор

2022-08-16 17:21 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Entities/ActionNotifier.cs
>      }
Она там еще как затычка в других ответах, пока пусть будет

2022-08-16 17:23 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +
Просто интересно, почему вебхук процессор отдельно 🤔

2022-08-16 19:02 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
А планируется много разных резалтов чтобы это было проблемой?

2022-08-16 19:11 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +        }
Будет обрабатываться разный набор эксепшенов, или для одинаковых эксепшенов в разных командах будут разные месседжи? Просто если первый вариант, то лучше всё таки сделать "мидлвар"-метод, потому что если эти наборы будут пересекаться, то будет ещё хуже с дубликацией. Если второй вариант, то weird but ok

2022-08-16 19:16 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Extensions/ServiceCollectionExtensions.cs
> +
Это не я писал, тоже хз, можешь объединить и его

2022-08-16 19:21 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Processors/IShreksCommandProcessor.cs
> +}
Именно так, через конструктор инжектить

2022-08-16 19:23 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Ну просто смысла не вижу
А статик методы, как предложил хрустик, действительно норм

2022-08-16 19:23 UTC, darksidersstrife commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +        }
На первый взгляд кажется второе, может и правда все будет настолько одинаково, что можно будет вынести

2022-08-16 19:25 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Processors/GithubCommandProcessor.cs
> +            return new BaseShreksCommandResult(true,
Со статик методами тоже пойдёт, но только "пойдёт" 🤷‍♂️

2022-08-16 19:27 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Commands/Contexts/BaseContext.cs
> +    public BaseContext(IMediator mediator, CancellationToken cancellationToken, User issuer)
bruh

```suggestion
    public BaseContext(IMediator mediator, User issuer, CancellationToken cancellationToken)
```

2022-08-16 19:32 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Commands/Contexts/BaseContext.cs
> +    public BaseContext(IMediator mediator, CancellationToken cancellationToken, User issuer)
Я наоборот сначала служебные хотел 🤔 
Ну то есть понимаю, что токен обычно последний)

2022-08-16 21:44 UTC, ronimizy approved these changes
Интерфейсы команд можно в один файл сложить. AcceptAsync. А так, кмк можно мержить.

2022-08-16 22:03 UTC, merged