Feat: add CQRS handlers
kysect/Shreks pull request #78
Opened 2022-08-11 11:44 UTC by Bibletoon

* Closes #30 

Не уверен насчёт расположения экстеншена для DbSet

2022-08-11 21:01 UTC, ronimizy requested changes
Реализация норм, за исключением пары мест где можно добавить асинки. В основном пару доёбов по кодстайлу, но они минорные, не так как на прошлом пре :)

2022-08-11 21:14 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganisationHandler.cs
> +using static Kysect.Shreks.Application.Abstractions.Github.Queries.GetSubjectCourseByOrganization;
маятину будешь за мат пояснять

2022-08-11 21:16 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetUserByUsernameHandler.cs
> +    }
Сделай кверю с получением юзера/ментора, или проверки прав _(юзер это или ментор)_, а не только получение айди по нику, пж.

2022-08-11 21:23 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetUserByUsernameHandler.cs
> +    }
да, тут стоит возвращать `UserDto`, а не просто юзера

2022-08-11 21:35 UTC, lipa44 requested changes
Основная просьба — добавить квери на получение юзера **и** ментора или получение прав (никнейм принадлежит юзеру **или** ментору) по нику/айди.

2022-08-11 21:35 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionPayloadHandler.cs
> +        submission.Payload = request.NewPayload;
А у нас будут какие-то проверки валидности пропертей, которые мы в сабмишен сетим?

2022-08-11 21:35 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganisationHandler.cs
> +    }
с асинхронной перегрузкой согласен, `Task.FromResult` выглядит ниоч

2022-08-11 21:35 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
приведением даты к UTC будем заниматься?)

2022-08-11 21:39 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetUserByUsernameHandler.cs
> +    }
+ нейминг кста. GetUserByUsername почему-то возвращает id

2022-08-11 21:43 UTC, lipa44 commented
И ещё наверное стоит добавить Гошин любимый `IAssemblyMaker`, в целом эта концепция мне понравилась.

2022-08-11 21:57 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetAssignmentByBranchNameAndSubjectCourseHandler.cs
> +                $"Assignment with branch name {request.BranchName} for subject course {request.SubjectCourseId} not found";
```csharp
var branchName = request.BranchName;
var subjectCourseId = request.SubjectCourseId;

return assignment is not null
        ? new Response(assignment.Id)
        : throw new EntityNotFoundException(
            $"Assignment with branch name {branchName} for subject course {subjectCourseId} not found");
```

?

2022-08-11 22:01 UTC, ronimizy commented
О, а экстеншн метода для регистрации хендлеров в di рили нет

2022-08-11 22:01 UTC, ronimizy commented
Хендлеры в принципе лучше сделать `internal`

2022-08-12 06:59 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetAssignmentByBranchNameAndSubjectCourseHandler.cs
> +                $"Assignment with branch name {request.BranchName} for subject course {request.SubjectCourseId} not found";
боже нет....

2022-08-12 07:02 UTC, Bibletoon commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganisationHandler.cs
> +using static Kysect.Shreks.Application.Abstractions.Github.Queries.GetSubjectCourseByOrganization;
> кто-то говорил что using static для пидорасов

![image](https://user-images.githubusercontent.com/45363221/184301848-e8f7ec6a-b723-47be-a3ee-006796e0bd51.png)

2022-08-12 07:03 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganisationHandler.cs
> +    }
> с асинхронной перегрузкой согласен, `Task.FromResult` выглядит ниоч

да тут даже не про выглядит ниоч, асинхронщина не просто так придумана была)

2022-08-12 15:38 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
Я обычно в таких ситуациях делаю абстракцию `IDateTimeProvider`. Вообще дату наверное стоит получать в хендлере, а не через команду.

2022-08-12 17:18 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Abstractions/DataAccess/GetEntityByIdExtension.cs
> +    public static async Task<T> GetByIdAsync<T>(this DbSet<T> dbSet, Guid id, CancellationToken cancellationToken = default)
Открыл первый файл, мне как бы уже достаточно для апрува!

2022-08-12 17:18 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Github/GetSubjectCourseByOrganisationHandler.cs
> +            .FirstOrDefault(gsc => gsc.GithubOrganizationName == request.OrganizationName);
Я бы рядом с GithubSubjectCourseAssociation написал экстеншен метод, чтобы тут код был такой:

```
var subjectCourseAssociation = _context.SubjectCourseAssociations.FindByGithubOrganizaiton(request.OrganizationName);
```

2022-08-12 17:18 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionPayloadHandler.cs
> +        submission.Payload = request.NewPayload;
Payload же максимально абстрактная штука. Хз что там может быть. Вроде обсуждали его замену на ассоциации по аналогии с остальным.

2022-08-12 19:12 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
> Я обычно в таких ситуациях делаю абстракцию `IDateTimeProvider`. Вообще дату наверное стоит получать в хендлере, а не через команду.

ну абстракция это хорошо, ток если мы этим всё же будем заниматься, то нам надо обрабатывать разные таймзоны (вдруг кто-то решит зайти под впн и абузить своё место в очереди)

кстати по этому поводу тык на @darksidersstrife

2022-08-12 19:21 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
Ну смотрите, у нас как бы источника для даты два - команда апдейта от препода и дата пришедшего ивента в вебхук
И как тут абузить-то)

2022-08-12 19:23 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
ну да, я в целом в итоге так и подумал)

2022-08-12 19:30 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
Но надо кстати подумать насчет таймзоны даты, введенной преподом

2022-08-12 20:18 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +        submission.SubmissionDateTime = request.NewDate;
Давайте ишую заведём и подумаем над тем, как не проиграть в таймзоны. В теории, нам достаточно по одной работать, но в базе, конечно, хочется в UTC всё хранить.

2022-08-12 20:53 UTC, darksidersstrife requested changes

2022-08-12 20:53 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +    public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
Только нам бы на апдейты сабмишена возвращать этот обновленый сабмишен

2022-08-12 20:53 UTC, darksidersstrife commented on Source/Application/Kysect.Shreks.Application.Handlers/Submissions/UpdateSubmissionDateHandler.cs
> +    public async Task<Unit> Handle(Command request, CancellationToken cancellationToken)
Всех апдейтов касается

2022-08-12 21:08 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Abstractions/DataAccess/GetEntityByIdExtension.cs
> +    public static async Task<T> GetByIdAsync<T>(this DbSet<T> dbSet, Guid id, CancellationToken cancellationToken = default)
а что если....)

```csharp
public static async Task<T> GetByIdAsync<T, TKey>(this DbSet<T> dbSet, TKey id, CancellationToken cancellationToken = default)
        where T : class
        where TKey : IEquatable<TKey>
```

2022-08-13 10:19 UTC, FrediKats approved these changes

2022-08-14 14:47 UTC, ronimizy commented on Source/Application/Kysect.Shreks.Application.Dto/Kysect.Shreks.Application.Dto.csproj
> +    </ItemGroup>
Эта зависимость убивает суть вынесения дто в отдельный объект, скорее бы автомаппер.....

2022-08-14 14:50 UTC, ronimizy approved these changes
Хотелось бы всё таки иметь `IDateTimeProvider`, ну или `IDateProvider`, если мы решили заменить в сабмишене `DateTime` на `DateOnly`, а так LGTM.

2022-08-15 10:44 UTC, hrrrrustic commented
@FrediKats Мерж?

2022-08-15 10:45 UTC, FrediKats commented
Можно.

2022-08-15 10:46 UTC, FrediKats commented on Source/Application/Kysect.Shreks.Application.Dto/Kysect.Shreks.Application.Dto.csproj
> +    </ItemGroup>
Завели ишую.

2022-08-15 10:47 UTC, merged