Refactor: Google Sheets
kysect/Shreks pull request #79
Opened 2022-08-11 19:42 UTC by Mihinator3000

2022-08-11 20:44 UTC, ronimizy requested changes
Местами чуток напрягает нейминг, но кроме тех что выделил комментами  – не критично

2022-08-11 20:44 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Extensions/ServiceCollectionExtensions.cs
>      }
Не фанат добавлять сегменты в di контейнер, особенно синглтонами. У тебя есть фабрики страниц, создавай инстансы в них через конструктор. Если хочется оптимизировать создание объектов используя сервис провайдер, можно принимать его в конструкторе фабрики и юзать `ActivatorUtilities`

2022-08-11 20:44 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Что-то это не DataFactory

2022-08-11 20:44 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/IStudentComponentFactory.cs
> +    public IComponent BuildRow(Student student);
```suggestion
   IComponent BuildRow(Student student);
```

2022-08-11 20:44 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ISpreadsheetIdProvider.cs
> +}
Fine for now, но у нас в системе всё-таки не одна таблица.

2022-08-11 20:44 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/ISheetController.cs
> +}
Имя контроллер ну прям оч не нравится, переименуй в сервис

2022-08-11 20:45 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ISpreadsheetIdProvider.cs
> +}
а. ну ладно тогда, надо подумать как лучше сделать

2022-08-11 20:45 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/ISheetController.cs
> +}
Я бы также назвал, но у нас уже есть SheetsService, они путаться будут так

2022-08-11 20:48 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Ну я бы также назвал SheetBuilder, но оно уже занято, у меня идей не осталось

2022-08-11 21:03 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Что насчёт `ISheetComponentFactory`? Оно ведь создаёт компоненты....

2022-08-11 21:04 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ISpreadsheetIdProvider.cs
> +}
Скорее всего это будет кверя в апликейшн, надо будет подумать как её реализовать, скорее всего надо будет добавить ещё один SubjectCourseAssociation для гугл таблиц

2022-08-11 21:05 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Tools/ISheetController.cs
> +}
`ISheetManagementService`?

2022-08-11 21:05 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/IStudentComponentFactory.cs
> +   IComponent BuildRow(Student student);
ы чёт я лишний пробел задел в саджесчене)

2022-08-11 21:06 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ISpreadsheetIdProvider.cs
> +}
Ок, я тогда пока этот конверсейшен резолвну

2022-08-11 21:09 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Ну оно так-то создает целые таблицы, а не компоненты, но ок..

2022-08-11 21:10 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Можно просто `ISheetFactory` на крайний случай

2022-08-11 21:11 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/ISheetDataFactory.cs
> +}
Ну Sheet тоже странно, не листы ведь создает, я ISheetComponentFactory оставил

2022-08-11 21:14 UTC, ronimizy commented
Сонар по делу говорит, добавь налчеки через `ArgumentNullException.ThrowIfNull`

2022-08-11 22:05 UTC, lipa44 commented on Source/Application/Kysect.Shreks.Application.Abstractions/Google/IGoogleTableAccessor.cs
> +public record struct Queue(IReadOnlyCollection<Submission> Submissions);
Несколько минут держал в голове вопрос, не будет ли проблем с использованием очереди.

Только тут заметил, что это наша структура. МБ переименовать во что-то более информативное?

StudentsQueue?)

2022-08-11 22:17 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ICultureInfoProvider.cs
> +    CultureInfo CultureInfo { get; }
Мб переделать в Get<ProviderType> методы? Так будет возможность реализовывать логику получения, в методе, а не в методах, которые будут инициализировать свойство.

2022-08-11 22:17 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ISpreadsheetIdProvider.cs
> +public interface ISpreadsheetIdProvider
сейм

2022-08-11 22:17 UTC, lipa44 commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +    .AddEntityGenerators(o =>
AddGoogleServices()?

2022-08-11 22:19 UTC, ronimizy commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +    .AddEntityGenerators(o =>
AddGoogleIntegration

2022-08-11 22:20 UTC, lipa44 commented on Source/Playground/Kysect.Shreks.Playground.Google/Program.cs
> +    .AddEntityGenerators(o =>
Как угодно

2022-08-12 09:46 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Providers/ICultureInfoProvider.cs
> +    CultureInfo CultureInfo { get; }
Ну так-то можно и в свойствах логику писать, но хорошо, я тоже думал так сначала сделать

2022-08-12 15:35 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetComponentFactory.cs
> +            CreateInstance<TotalPointsSegment>(serviceProvider)
Не не не, тут с `import static` переборщил

2022-08-12 15:55 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetComponentFactory.cs
> +            CreateInstance<TotalPointsSegment>(serviceProvider)
Ладно, но будет достаточно громоздко смотреться

2022-08-12 15:59 UTC, ronimizy commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetComponentFactory.cs
> +            CreateInstance<TotalPointsSegment>(serviceProvider)
Да не, норм

2022-08-12 16:02 UTC, Mihinator3000 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Google/Factories/PointsSheetComponentFactory.cs
> +            CreateInstance<TotalPointsSegment>(serviceProvider)
Ну так, копипаста небольшая

2022-08-12 16:05 UTC, ronimizy approved these changes

2022-08-12 17:21 UTC, FrediKats reviewed
А можно как-то описать, что мы получили то в итоге? Какой-то гайд по тому, как это всё использовать / по тому как оно с коробки работает, какие-то скрины. Хочется зафиксировать знания в доке.

2022-08-12 18:19 UTC, Mihinator3000 commented
@FrediKats по тому как использовать, в плейграунде я проект специально сделал, там вроде все прописано. Скрины таблиц прикрепляю здесь.

Очередь:
![image](https://user-images.githubusercontent.com/70411602/184419797-19a91c25-5883-4153-b27a-d260ddde9fb0.png)

Баллы:
![image](https://user-images.githubusercontent.com/70411602/184419824-615f6598-d0f2-4420-b6a8-ba4b5a851837.png)

2022-08-12 20:16 UTC, FrediKats approved these changes
Закинь плиз (можно отдельным PR) md файл в тех доки с описанием того, где конфигается, что нужно для запуска (откуда-то токены достать и т.д.). НУ и скрины.

В остальном всё круто, спасибо!

2022-08-13 10:47 UTC, merged