Fix: Entity generators
kysect/Shreks pull request #80
Opened 2022-08-11 19:54 UTC by Mihinator3000

2022-08-11 20:21 UTC, ronimizy requested changes

2022-08-11 20:21 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/StudentGroupGenerator.cs
> +        return new StudentGroup($"M{groupNumber}");
Минимальная наверное не 0

2022-08-11 20:21 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/NameExtensions.cs
> +    }
Это чёт очень сомнительная логика. Кмк с Username лучше чем просто с ещё одним именем. Данные нужны реалистично выглядящие, прям супер совпадение с реальностью не требуется.

2022-08-11 20:21 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociations/GithubUserAssociationGenerator.cs
> +            .ToList();
Думаю что лучше юзать `.Skip(index).First()`

2022-08-11 20:21 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/UserAssociations/IsuUserAssociationGenerator.cs
> +            .ToList();
same ^

2022-08-11 20:25 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/NameExtensions.cs
> +    }
Ну в английском как раз MiddleName обычно как FirstName звучит + в `UserName`е цифры, не понимаю зачем его тут использовать

2022-08-11 20:47 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/Extensions/NameExtensions.cs
> +    }
Ну мы то не из Англии) В фейкере можно поставить русскую локаль. В принципе без разницы какое именно будет отчество, главное чтобы данные были, просто не вижу смысла добавлять код и логику в местах где это не нужно

2022-08-11 20:48 UTC, ronimizy approved these changes

2022-08-12 08:12 UTC, luck-o-o-luck approved these changes
В целом - выглядит как ок. Всё еще не понимаю, чем не угодил Person.FirstName и тд, потому что, кажется, это не так уж и сильно важно. Оставила один коммент, но не уверена, что он имеет место быть.

2022-08-12 08:12 UTC, luck-o-o-luck commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/AssignmentGenerator.cs
> +            (index + 1).ToString(),
а ловко ты это придумал...

2022-08-12 08:12 UTC, luck-o-o-luck commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
> +        var assignment = _faker.PickRandom<Assignment>(_assignmentGenerator.GeneratedEntities);
Мы брали предыдущее, чтобы уменьшить вероятность того, что пикнутся две одинаковые пары. Мб предыдущее оставить? Возможно, я не права.

2022-08-12 08:12 UTC, luck-o-o-luck commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/MentorGenerator.cs
> +            _faker.Name.MiddleName(),
Ладно.

2022-08-12 09:20 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
> +        var assignment = _faker.PickRandom<Assignment>(_assignmentGenerator.GeneratedEntities);
В прошлой генерации все создавалось слишком по порядку, то есть сначала генерились все сабмишены для 1 студента (по 1 на лабу), потом для другого, и тд. В реальной же жизни не у всех есть сабмишены на каждую лабу, а если есть, то их может быть несколько

2022-08-12 09:32 UTC, Mihinator3000 commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/User/MentorGenerator.cs
> +            _faker.Name.MiddleName(),
К вопросу, чем не угодил Person.FirstName, и тому подобные. У нас это были не функции, а поля. А все поля в фейкере генерируются 1 раз и остаются такими же при каждом его вызове, а учитывая что он у нас прокидывается как синглтон, то он никогда и не пересоздается. (Думаю поля нужны, когда мы задаем фейкер для класса через new Faker<ClassName>().RuleFor)

2022-08-12 15:33 UTC, ronimizy commented on Source/Infrastructure/Kysect.Shreks.Seeding/EntityGenerators/Study/SubmissionGenerator.cs
> +        var assignment = _faker.PickRandom<Assignment>(_assignmentGenerator.GeneratedEntities);
> Мы брали предыдущее, чтобы уменьшить вероятность того, что пикнутся две одинаковые пары. Мб предыдущее оставить? Возможно, я не права.

Для сабмишена норм если два с одинаковыми студентом и заданием будут.

2022-08-12 17:22 UTC, FrediKats approved these changes
Добавить нечего.

2022-08-12 17:54 UTC, merged