Chore: add cred store
kysect/Shreks pull request #81
Opened 2022-08-13 00:21 UTC by darksidersstrife

2022-08-13 00:22 UTC, darksidersstrife commented
closes #34

2022-08-13 01:13 UTC, lipa44 requested changes

2022-08-13 01:13 UTC, lipa44 commented on Source/Infrastructure/Integration/Kysect.Shreks.Integration.Github/Client/InstallationClientFactory.cs
>          var accessToken = await _gitHubAppClient.GitHubApps.CreateInstallationToken(installationId);
убери токен тогда, раз он теперь не юзается

2022-08-13 11:21 UTC, FrediKats commented
@darksidersstrife, тебя CI  забулил, если что. Поправить бы.

2022-08-13 12:16 UTC, darksidersstrife commented
И очень правильно забуллил, спасибо ему

2022-08-13 12:32 UTC, darksidersstrife commented
Блин блинский, еще async надо убрать

2022-08-13 19:18 UTC, darksidersstrife commented
Я там по всему пути убрал эвейты, или стоило просто сделать Task.FromResult для гибкости апи?

2022-08-13 21:55 UTC, lipa44 commented
> Я там по всему пути убрал эвейты, или стоило просто сделать Task.FromResult для гибкости апи?

Я тоже над этим подумал. Конкретно в этом случае я бы наверное оставил `Task`..., чтобы работа с кешем была асинхронной как минимум.

2022-08-14 07:03 UTC, FrediKats commented
Но если там ничего асинхронно не выполняется, то зачем пытаться натягивать асинки? Просто эе оверхед получим на стейт машине без профита.

2022-08-14 14:06 UTC, FrediKats approved these changes
Если нужно будет - вернём.

2022-08-14 14:06 UTC, merged